conf	article (goes_through,activity,ref) (has_author,human,ref) (structure_created_by,human,ref) (is_sent_to,human,ref) (gives_classification,classification,ref) (is_created_in,activity,ref) 
conf	Person (hasHomePage,String,attribute) (hasSurname,String,attribute) (hasEmail,String,attribute) (has_the_first_name,String,attribute) (has_gender,EEnum,attribute) (hasFax,String,attribute) (has_the_last_name,String,attribute) (hasPhone,String,attribute) (has_an_email,String,attribute) (hasFirstName,String,attribute) (email,String,attribute) (add,Person,ref) (inverse_of_add,Thing,ref) (use,Document,ref) (employedBy,Organization,ref) (execute,Thing,ref) (remove,Thing,ref) (contributes,Conference_document,ref) (modify,Thing,ref) (hasConflictOfInterest,Document,ref) (added_by,Person,ref) (get,Inforamtion,ref) (take_part_in,Event,ref) (send,Activity,ref) (register,Account,ref) 
conf	activity (has_intensity,intensity,ref) (is_followed_by,activity,ref) (is_performed_by,human,ref) (is_supervised_by,human,ref) (has_result,article,ref) (is_monitored_by,human,ref) 
conf	Important_dates (is_an_ending_date,date,ref) (is_a_full_paper_submission_date,date,ref) (is_an_abstract_submission_date,date,ref) (is_a_date_of_camera_ready_paper_submission,date,ref) (belong_to_a_conference_volume,Conference_volume,ref) (is_a_date_of_acceptance_announcement,date,ref) (is_a_starting_date,date,ref) 
conf	human (e-mail,String,attribute) (last_name,String,attribute) (first_name,String,attribute) (supervises,activity,ref) (performs_activity,activity,ref) (has_topic_of_interest,topic,ref) (is_employed_in,institute,ref) (is_author_of,article,ref) 
conf	Reviewer (readPaper,Paper,ref) (writeReview,Review,ref) (assignExternalReviewer,ExternalReviewer,ref) (invites_co-reviewers,Reviewer,ref) (adjustBid,Bid,ref) (has_a_review_reference_or_expertise,Thing,ref) (invited_by,Reviewer,ref) (hasBeenAssigned,Paper,ref) (assignedByAdministrator,Administrator,ref) 
conf	Paper (title,String,attribute) (paperID,unsignedLong,attribute) (rejectedBy,Administrator,ref) (hasCo-author,Co-author,ref) (hasSubjectArea,SubjectArea,ref) (hasBid,Bid,ref) (hasAuthor,Author,ref) (readByReviewer,Reviewer,ref) (hasDecision,Decision,ref) (acceptedBy,Administrator,ref) (assignedTo,Reviewer,ref) (readByMeta-Reviewer,Meta-Reviewer,ref) 
conf	Event (ends_on,String,attribute) (starts_on,String,attribute) (approved_by,Administrator,ref) (conists_of,Event_Tracks,ref) (defined_by,Event_Setup,ref) (confirmed_by,Approval_Email,ref) 
conf	Contribution (contactEmail,String,attribute) (hasKeyword,String,attribute) (remark,String,attribute) (abstract,String,attribute) (hasTitle,String,attribute) (writtenBy,Author,ref) (dealsWith,Topic,ref) 
