tex	BibtexEntry (Pages,EEString,attribute) (publicationFilePath,EEString,attribute) (Year,EEString,attribute) (Volume,EEString,attribute) (Title,EEString,attribute) (Author,EEString,attribute) (Text,EEString,attribute) (Journal,EEString,attribute) (Tags,Tag,ref)
