tex	ArtOuvrageType (titouv,EString,attribute) (edsci,EString,attribute) (serie,EString,attribute) (annee,EString,attribute) (edcom,EString,attribute) (urldoi,EString,attribute)
tex	Auteur (autrePrenom,EString,attribute) (urlPerso,EString,attribute) (nom,EString,attribute) (prenom,EString,attribute) (email,EString,attribute) (lab,Laboratoire,ref)
tex	MetaType (isEpj,Integer,attribute) (langue,EString,attribute) (isEpl,EString,attribute) (title,EString,attribute) (classification,EString,attribute) (financement,EString,attribute) (idext,EString,attribute) (datevisible,DateVisibleEnum,attribute) (researchteam,EString,attribute) (collaboration,EString,attribute) (comment,EString,attribute) (refInterne,EString,attribute) (keyword,EString,attribute)
