tex	Book (volume,null,ref) (editor,null,ref) (address,null,ref) (author,null,ref) (series,null,ref) (publisher,null,ref) (edition,null,ref)
tex	BibType (note,null,ref) (month,null,ref) (year,null,ref) (title,null,ref) (key,null,ref) (citeKey,null,ref)
tex	Inbook (editor,EBoolean,attribute) (author,EBoolean,attribute) (volume,null,ref) (chapter,null,ref) (pages,null,ref) (address,null,ref) (series,null,ref) (publisher,null,ref) (edition,null,ref)
