uml	Automaton (eventPatternId,EString,attribute) (initialState,InitState,ref) (finalStates,FinalState,ref) (eventTokens,EventToken,ref) (timedZones,TimedZone,ref) (states,State,ref) (trapState,TrapState,ref) 
uml	State (label,EString,attribute) (outStateOf,TimedZone,ref) (inStateOf,TimedZone,ref) (lastProcessedEvent,null,ref) (inTransitions,Transition,ref) (outTransitions,Transition,ref) (eventTokens,EventToken,ref) 
