office	StyleLayout (fontName,EString,attribute) (lineStyle,LineStyle,attribute) (fontBold,YesNoBool,attribute) (transparency,EDouble,attribute) (fontSize,EInt,attribute) (fontItalic,YesNoBool,attribute) (lineWidth,EInt,attribute) (gradient_orientation,GradientAllignment,attribute) (background,ColorOrGradient,ref) (lineColor,ColorWithTransparency,ref) (highlighting,HighlightingValues,ref) (fontColor,Color,ref) 
