tex	Researcher (forName,EString,attribute) (name,EString,attribute) (skills,Skill,ref) (res_papers,Paper,ref) (res_position,Position,ref) (reviews,Review,ref) (collaborations,Collaboration,ref) (writes,Write,ref)
tex	Paper (citedBy,Paper,ref) (keywords,PaperKeyword,ref) (progress,Progress,ref) (state,State,ref) (paragraphs,Paragraph,ref) (authors,Researcher,ref) 

