<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="appBuilderDSL" nsURI="http://www.nagarro.com/AppBuilderDSL"
    nsPrefix="appBuilderDSL">
  <eClassifiers xsi:type="ecore:EClass" name="AppBuilder">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//AbstractElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamespaceDeclation" eSuperTypes="#//AbstractElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="#//AbstractElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="business" eType="#//Business"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ui" eType="#//Ui" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Business">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Service" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service"/>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceService" eSuperTypes="#//Service">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ui">
    <eStructuralFeatures xsi:type="ecore:EReference" name="main" eType="#//Main" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//Service" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="screens" upperBound="-1"
        eType="#//Screen" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Main">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="appName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="appVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="devices" unique="false"
        upperBound="-1" eType="#//Device"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="screen" eType="#//Screen"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generalStyle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Device">
    <eLiterals name="iphone" literal="iphone"/>
    <eLiterals name="ipad" value="1" literal="ipad"/>
    <eLiterals name="android4" value="2" literal="android4"/>
    <eLiterals name="android2" value="3" literal="android2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Screen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleScreen" eSuperTypes="#//Screen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entryParameters" eType="#//EntryParameters"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//Model"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="view" eType="#//View" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controller" eType="#//Controller"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntryParameters">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Controller">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initAction" eType="#//InitAction"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validator" eType="#//Validator"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="databindings" upperBound="-1"
        eType="#//DataBinding" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uiListenerBindingss" upperBound="-1"
        eType="#//UiListenerBinding" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validationBindings" upperBound="-1"
        eType="#//ValidationBinding" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1"
        eType="#//Instruction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidationBinding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Condition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="control" eType="#//Control"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="controlAccess" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UiListenerBinding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//Action"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="control" eType="#//Control"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="controlAccess" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataBinding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="control" eType="#//Control"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="controlAccess" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleDataBinding" eSuperTypes="#//DataBinding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelAccess" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumDataBinding" eSuperTypes="#//DataBinding">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enumClassName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Validator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" upperBound="-1"
        eType="#//Condition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditionExpression" eType="#//ConditionExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleConditionExpression" eSuperTypes="#//ConditionExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeConditionExpression" eSuperTypes="#//ConditionExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" unique="false"
        upperBound="-1" eType="#//Condition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="UiAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1"
        eType="#//Instruction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="SetInstruction" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelAccess" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignment" eType="#//SetInstructionAssignment"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Navigate" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="screen" eType="#//Screen"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="params" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecuteAction" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//Action"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetInstructionAssignment"/>
  <eClassifiers xsi:type="ecore:EClass" name="RestCall" eSuperTypes="#//SetInstructionAssignment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlValue" eSuperTypes="#//SetInstructionAssignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="control" eType="#//Control"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="controlAccess" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="View">
    <eStructuralFeatures xsi:type="ecore:EReference" name="layouts" upperBound="-1"
        eType="#//Layout" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Layout" eSuperTypes="#//Control">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controls" upperBound="-1"
        eType="#//Control" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GridLayout" eSuperTypes="#//Layout">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columns" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RowLayout" eSuperTypes="#//Layout"/>
  <eClassifiers xsi:type="ecore:EClass" name="Control"/>
  <eClassifiers xsi:type="ecore:EClass" name="ScreenLayout" eSuperTypes="#//Control">
    <eStructuralFeatures xsi:type="ecore:EReference" name="screen" eType="#//Screen"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="List" eSuperTypes="#//Control">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelprovider" eType="#//Value"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cssStyle" eType="#//Value"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tooltip" eType="#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value"/>
  <eClassifiers xsi:type="ecore:EClass" name="DynamicValue" eSuperTypes="#//SetInstructionAssignment #//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="terms" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Text" eSuperTypes="#//Control">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cssStyle" eType="#//Value"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceKey" eType="#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Button" eSuperTypes="#//Control">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cssStyle" eType="#//Value"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceKey" eType="#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Label" eSuperTypes="#//Control">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceKey" eType="#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeScreen" eSuperTypes="#//Screen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="layouts" upperBound="-1"
        eType="#//Layout" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Feature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="many" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type"/>
  </eClassifiers>
</ecore:EPackage>
