<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="AssistantMVC"
    nsURI="http://gts.inf.um.es/test/assistant_mvc" nsPrefix="mvc">
  <eClassifiers xsi:type="ecore:EClass" name="Exam" eSuperTypes="#//Observable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="examItems" upperBound="-1"
        eType="#//ExamItem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controllers" upperBound="-1"
        eType="#//Controller" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="views" upperBound="-1"
        eType="#//View" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExamItem" abstract="true" eSuperTypes="#//Observable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="question" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Open" eSuperTypes="#//ExamItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="MultipleChoice" eSuperTypes="#//ExamItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="Observable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="observers" upperBound="-1"
        eType="#//Observer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Observer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Controller" abstract="true" eSuperTypes="#//Observer"/>
  <eClassifiers xsi:type="ecore:EClass" name="View" abstract="true" eSuperTypes="#//Observer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controller" eType="#//Controller"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExamController" eSuperTypes="#//Controller"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExamItemController" abstract="true"
      eSuperTypes="#//Controller"/>
  <eClassifiers xsi:type="ecore:EClass" name="MultipleChoiceController" eSuperTypes="#//ExamItemController"/>
  <eClassifiers xsi:type="ecore:EClass" name="OpenController" eSuperTypes="#//ExamItemController"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExamView" eSuperTypes="#//View"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExamItemView" eSuperTypes="#//View"/>
</ecore:EPackage>
