<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cvlmodel" nsURI="http://www.example.org/CVLModel" nsPrefix="cvlmodel">
  <eClassifiers xsi:type="ecore:EClass" name="VSpec" abstract="true">
    <eOperations name="isRoot" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eOperations name="isCloneable" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eOperations name="isClon" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mandatory" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groupMultiplicity" eType="#//Multiplicity"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//VSpec"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//VSpec"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Choice" eSuperTypes="#//VSpec"/>
  <eClassifiers xsi:type="ecore:EClass" name="Multiplicity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//VSpec"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//VSpec">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//PrimitiveTypeEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VClassifier" eSuperTypes="#//VSpec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instanceMultiplicity" eType="#//Multiplicity"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PrimitiveTypeEnum">
    <eLiterals name="String"/>
    <eLiterals name="Boolean"/>
    <eLiterals name="Integer"/>
    <eLiterals name="Real"/>
    <eLiterals name="UnlimitedNatural"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSpecResolution" abstract="true">
    <eOperations name="isPossitivelyResolved" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resolvedVSpec" lowerBound="1"
        eType="#//VSpec"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChoiceResolution" eSuperTypes="#//VSpecResolution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="decision" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableResolution" eSuperTypes="#//VSpecResolution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnySimpleType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VClassifierResolution" eSuperTypes="#//VSpecResolution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instance" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariationPoint" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binding" lowerBound="1"
        eType="#//VSpec"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="#//StringToMOFRefMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelTransformationURL"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelTransformationSourceURL"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="negativeVariability" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MOFRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringToMOFRefMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" unique="false" lowerBound="1"
        eType="#//MOFRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectExistence" eSuperTypes="#//VariationPoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSpecTree">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vspecs" upperBound="-1"
        eType="#//VSpec" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" eType="#//VSpec"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResolutionModel">
    <eOperations name="getVSpecResolutionsForVSpec" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ENTITIES">
      <eParameters name="vspec" eType="#//VSpec"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resolutions" upperBound="-1"
        eType="#//VSpecResolution" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resolvedVSpec" lowerBound="1"
        eType="#//VSpecTree"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CVLModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vspecTree" lowerBound="1"
        eType="#//VSpecTree" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variationPoints" upperBound="-1"
        eType="#//VariationPoint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        iD="true"/>
  </eClassifiers>
</ecore:EPackage>
