<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="design" nsURI="http://www.example.org/design" nsPrefix="design">
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//Classifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//Types"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnType" eType="#//Types"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Design">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Classifier" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
        eType="#//Relation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" eType="#//Languages"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="#//Relation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Generalization" eSuperTypes="#//Relation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dependency" eSuperTypes="#//Relation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Composition" eSuperTypes="#//Relation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Relation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Classifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Classifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aggregation" eSuperTypes="#//Relation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Realization" eSuperTypes="#//Relation"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Languages">
    <eLiterals name="Java" literal="Java"/>
    <eLiterals name="CS" value="1" literal="CS"/>
    <eLiterals name="Python" value="2" literal="Python"/>
    <eLiterals name="CPP" value="3" literal="CPP"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Types">
    <eLiterals name="int"/>
    <eLiterals name="long" value="1" literal="long"/>
    <eLiterals name="double" value="2"/>
    <eLiterals name="float" value="3"/>
    <eLiterals name="string" value="4" literal="String"/>
    <eLiterals name="boolean" value="5"/>
    <eLiterals name="void" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AccessModifiers">
    <eLiterals name="public" value="1"/>
    <eLiterals name="protected" value="2"/>
    <eLiterals name="private" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="#//Classifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Classifier" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//Operation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessModifier" eType="#//AccessModifiers"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
