<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="DictionaryLanguage" nsURI="platform:/plugin/DictionaryLanguage/model/DictionaryLanguage.ecore"
    nsPrefix="DictionaryLanguage">
  <eClassifiers xsi:type="ecore:EClass" name="Author">
    <eStructuralFeatures xsi:type="ecore:EReference" name="library" lowerBound="1"
        eType="#//Library" eOpposite="#//Library/author"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dictionary" upperBound="-1"
        eType="#//Dictionary" eOpposite="#//Dictionary/author"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dictionary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="shelf" lowerBound="1" eType="#//Shelf"
        eOpposite="#//Shelf/dictionary"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" lowerBound="1"
        eType="#//Author" eOpposite="#//Author/dictionary"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" upperBound="-1"
        eType="#//Entry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Library">
    <eStructuralFeatures xsi:type="ecore:EReference" name="shelf" upperBound="-1"
        eType="#//Shelf" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" upperBound="-1"
        eType="#//Author" containment="true" eOpposite="#//Author/library"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Shelf">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dictionary" upperBound="-1"
        eType="#//Dictionary" containment="true" eOpposite="#//Dictionary/shelf"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
