<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ed2" nsURI="http://ed2/1.0" nsPrefix="ed2">
  <eClassifiers xsi:type="ecore:EClass" name="EDD">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="treeObjects" upperBound="-1"
        eType="#//TreeObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="treeParents" upperBound="-1"
        eType="#//TreeParent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TreeElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TreeElementType"
        defaultValueLiteral="empty"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//TreeElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leaves" upperBound="-1"
        eType="#//Leaf" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Leaf" eSuperTypes="#//TreeElement"/>
  <eClassifiers xsi:type="ecore:EEnum" name="TreeElementType">
    <eLiterals name="empty"/>
    <eLiterals name="yes" value="1"/>
    <eLiterals name="no" value="2"/>
    <eLiterals name="trusted" value="3"/>
    <eLiterals name="dont_know" value="4" literal="dont know"/>
    <eLiterals name="inadmissible" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TreeParent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="treeObjects" upperBound="-1"
        eType="#//TreeObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="treeParents" upperBound="-1"
        eType="#//TreeParent"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TreeElementType"
        defaultValueLiteral="empty"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TreeObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TreeElementType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ED2">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="treeElements" upperBound="-1"
        eType="#//TreeElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eAnnotations source="root"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ed2" eType="#//ED2" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
