<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="EFM" nsURI="http://example.org/EFM" nsPrefix="EFM">
  <eClassifiers xsi:type="ecore:EClass" name="FeatureModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//FMConstraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootFeature" lowerBound="1"
        eType="#//Feature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FMElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="#//FMElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subFeatures" upperBound="-1"
        eType="#//Feature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureCardinality" lowerBound="1"
        eType="#//FeatCardinality" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeFeature" upperBound="-1"
        eType="#//NodeFeature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exclusive" eSuperTypes="#//Alternative"/>
  <eClassifiers xsi:type="ecore:EClass" name="Alternative" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variants" lowerBound="1"
        upperBound="-1" eType="#//Feature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cardinality" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinalityMin" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinalityMax" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="configValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//FMElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="ecore:EClass Type.ecore#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FMConstraint" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanConstraint" abstract="true" eSuperTypes="#//FMConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatCardinality" eSuperTypes="#//Cardinality"/>
  <eClassifiers xsi:type="ecore:EClass" name="Implies" eSuperTypes="#//BooleanConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Excludes" eSuperTypes="#//BooleanConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Requires" eSuperTypes="#//FMConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" lowerBound="1"
        upperBound="2" eType="#//Operation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="#//Operation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//LogicalOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Functional" eSuperTypes="#//FMConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//Operator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comparison" eSuperTypes="#//FMConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//FMElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//FMElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//ComparisonOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RangeOperation" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" eType="#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueOperation" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="ecore:EClass Type.ecore#//IntValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComparisonOperator">
    <eLiterals name="equal" literal="equal"/>
    <eLiterals name="geq" value="1" literal="geq"/>
    <eLiterals name="gt" value="2" literal="gt"/>
    <eLiterals name="leq" value="3" literal="leq"/>
    <eLiterals name="lt" value="4" literal="lt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Operator">
    <eLiterals name="select" literal="select"/>
    <eLiterals name="add" value="1"/>
    <eLiterals name="remove" value="2"/>
    <eLiterals name="multiply" value="3"/>
    <eLiterals name="divide" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LogicalOperator">
    <eLiterals name="void" literal="void"/>
    <eLiterals name="and" value="1" literal="and"/>
    <eLiterals name="or" value="2" literal="or"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Colocated" eSuperTypes="#//FMConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromAgain" upperBound="-1"
        eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeFeature" eSuperTypes="#//NodeFeatureElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="NodeAttributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="NodeCardinalities" lowerBound="1"
        eType="#//FeatCardinality" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="HostedBy" eType="#//HostedBy"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="NotHostedBy" eType="#//NotHostedBy"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HostedBy" eSuperTypes="#//FMConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" upperBound="-1"
        eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//NodeFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Separated" eSuperTypes="#//FMConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceVerification" eSuperTypes="#//FMConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromAtt" lowerBound="1"
        upperBound="-1" eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extF" lowerBound="1" eType="#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NotHostedBy" eSuperTypes="#//FMConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extF" lowerBound="1" eType="#//NodeFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="From" lowerBound="1" upperBound="-1"
        eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeFeatureElement" abstract="true"/>
</ecore:EPackage>
