<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MySM" nsURI="http://hs-fulda.de/ai/mdd/statemachine" nsPrefix="SM">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Statemachine" eSuperTypes="#//Region">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" lowerBound="1"
        upperBound="-1" eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" lowerBound="1"
        upperBound="-1" eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Region">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" lowerBound="1"
        upperBound="-1" eType="#//State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initial" lowerBound="1"
        eType="#//Pseudostate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vertex">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoings" lowerBound="1"
        upperBound="-1" eType="#//Transition" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pseudostate" eSuperTypes="#//Vertex">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="psId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="#//Pseudokind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Pseudokind">
    <eLiterals name="Initial"/>
    <eLiterals name="End" value="1"/>
    <eLiterals name="Exit" value="2"/>
    <eLiterals name="DeepHistory" value="3"/>
    <eLiterals name="ShallowHistory" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="#//Vertex">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexSate" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="region" lowerBound="1"
        upperBound="-1" eType="#//Region" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Vertex"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Vertex"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabeledTransition" eSuperTypes="#//Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="#//Action"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
