<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="farmbot_modeling" nsURI="http://www.example.org/farmbot_modeling"
    nsPrefix="farmbot_modeling">
  <eClassifiers xsi:type="ecore:EClass" name="Farmbot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1"
        eType="#//Instruction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instruction" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceCommand" abstract="true" eSuperTypes="#//Command #//SequenceInstruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Move" abstract="true" eSuperTypes="#//SequenceCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="z" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TurnOnDigital" eSuperTypes="#//SequenceCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TurnOff" eSuperTypes="#//SequenceCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MoveRelative" eSuperTypes="#//Move"/>
  <eClassifiers xsi:type="ecore:EClass" name="FindHome" eSuperTypes="#//SequenceCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="axis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequenceInstructions" upperBound="-1"
        eType="#//SequenceInstruction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="If" eSuperTypes="#//SequenceInstruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="booleanExpression" lowerBound="1"
        eType="#//BooleanExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="then" eType="#//ExecuteSequence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//ExecuteSequence"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MoveAbsolute" eSuperTypes="#//Move"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExecuteSequence" eSuperTypes="#//SequenceCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wait" eSuperTypes="#//SequenceCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanExpression" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="axe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pinNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SendMessage" eSuperTypes="#//SequenceCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RunFarmware" eSuperTypes="#//SequenceCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TakePhoto" eSuperTypes="#//SequenceCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceInstruction" abstract="true"
      eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="IsEqualTo" eSuperTypes="#//BooleanExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="IsNotEqualTo" eSuperTypes="#//BooleanExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="IsGreaterThan" eSuperTypes="#//BooleanExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="IsLowerThan" eSuperTypes="#//BooleanExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Schedule" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sequence" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repeat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repeatUnit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Command" abstract="true" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="ListSequences" eSuperTypes="#//Command"/>
  <eClassifiers xsi:type="ecore:EClass" name="ListScheduledEvents" eSuperTypes="#//Command"/>
  <eClassifiers xsi:type="ecore:EClass" name="TurnOnAnalog" eSuperTypes="#//SequenceCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
