<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="farrusco" nsURI="http://farrusco/1.0" nsPrefix="farrusco">
  <eAnnotations source="gmf">
    <details key="farr" value="usco"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Robot">
    <eAnnotations source="gmf.diagram">
      <details key="farr" value="usco"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionChild" upperBound="-1"
        eType="#//ActionChild" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" upperBound="-1"
        eType="#//Child" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" upperBound="-1" eType="#//Next"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="Child">
    <eAnnotations source="gmf.link">
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="style" value="dot"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" upperBound="-1"
        eType="#//Behavior"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" upperBound="-1"
        eType="#//Behavior"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Next">
    <eAnnotations source="gmf.link">
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="target.decoration" value="arrow"/>
      <details key="style" value="dot"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" upperBound="-1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" upperBound="-1"
        eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionChild">
    <eAnnotations source="gmf.link">
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="style" value="dot"/>
      <details key="width" value="2"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Behavior"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" upperBound="-1"
        eType="#//Action"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Behavior" abstract="true" eSuperTypes="#//Node">
    <eAnnotations source="gmf.node">
      <details key="figure" value="rounded"/>
      <details key="resizable" value="false"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="gmf.label">
        <details key="label" value="Name"/>
        <details key="label.text" value="controlo"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Prior" eSuperTypes="#//Behavior">
    <eAnnotations source="gmf.node">
      <details key="label" value="Name"/>
      <details key="label.readOnly" value="true"/>
      <details key="tool.name" value="Prioridade"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Paralell" eSuperTypes="#//Behavior">
    <eAnnotations source="gmf.node">
      <details key="label" value="Name"/>
      <details key="label.readOnly" value="true"/>
      <details key="tool.name" value="Paralelo"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sequential" eSuperTypes="#//Behavior">
    <eAnnotations source="gmf.node">
      <details key="label" value="Name"/>
      <details key="label.readOnly" value="true"/>
      <details key="tool.name" value="Sequencia"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateOverride" eSuperTypes="#//Behavior">
    <eAnnotations source="gmf.node">
      <details key="label" value="Name"/>
      <details key="label.readOnly" value="true"/>
      <details key="tool.name" value="Mudanca de Estado"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="succ_policy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="gmf.label">
        <details key="label.text" value="0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fail_policy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="gmf.label">
        <details key="label.text" value="0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="runn_policy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="gmf.label">
        <details key="label.text" value="0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true" eSuperTypes="#//Node">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="figure" value="rectangle"/>
      <details key="resizable" value="false"/>
      <details key="label.readOnly" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" abstract="true" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="IRdist" eSuperTypes="#//Condition">
    <eAnnotations source="gmf.node">
      <details key="label.text" value="255, 255"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distancia" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="gmf.label">
        <details key="label.text" value="10"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="how_sucess" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="gmf.label">
        <details key="label.text" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RightBumper" eSuperTypes="#//Condition">
    <eAnnotations source="gmf.node">
      <details key="label.text" value="BumperDireito"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LeftBumper" eSuperTypes="#//Condition">
    <eAnnotations source="gmf.node">
      <details key="label.text" value="BumperEsquerdo"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wait" eSuperTypes="#//Condition">
    <eAnnotations source="gmf.node">
      <details key="label.text" value="Wait"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="gmf.label">
        <details key="label.text" value="500"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actuate" abstract="true" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="Motors" eSuperTypes="#//Actuate">
    <eAnnotations source="gmf.node">
      <details key="label.text" value="255, 255"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MotorLeft" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="255">
      <eAnnotations source="gmf.label">
        <details key="label.text" value="255"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MotorRight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="255">
      <eAnnotations source="gmf.label">
        <details key="label.text" value="255"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServoRange" eSuperTypes="#//Actuate">
    <eAnnotations source="gmf.node">
      <details key="label.text" value="Servo"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="gmf.label">
        <details key="label.text" value="0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="gmf.label">
        <details key="label.text" value="160"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="gmf.label">
        <details key="label.text" value="10"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LED" eSuperTypes="#//Actuate">
    <eAnnotations source="gmf.node">
      <details key="label.text" value="LED"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="on_off" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="gmf.label">
        <details key="label.text" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
