<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fiacre"
    nsURI="http://org.topcased.fiacre" nsPrefix="fiacre">
  <eClassifiers xsi:type="ecore:EClass" name="Program">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" lowerBound="1"
        upperBound="-1" eType="#//Declaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" lowerBound="1" eType="#//NodeDecl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Declaration" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeDecl" abstract="true" eSuperTypes="#//Declaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg" upperBound="-1" eType="#//ArgumentVariable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" upperBound="-1" eType="#//LocalVariable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" upperBound="-1" eType="#//ParamPortDecl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localPort" upperBound="-1"
        eType="#//LocalPortDecl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initAction" lowerBound="1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDecl" eSuperTypes="#//Declaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="is" lowerBound="1" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChannelDecl" eSuperTypes="#//Declaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="is" lowerBound="1" eType="#//Channel"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentDecl" eSuperTypes="#//NodeDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//Composition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="priority" upperBound="-1"
        eType="#//Priority" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessDecl" eSuperTypes="#//NodeDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" upperBound="-1"
        eType="#//State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
        eType="#//Transition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortDecl" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="channel" lowerBound="1"
        eType="#//Channel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="in" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="out" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArgumentVariable" eSuperTypes="#//Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="read" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="write" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalVariable" eSuperTypes="#//Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constant" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initializer" eType="#//Exp"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Composition" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Par" eSuperTypes="#//Composition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg" lowerBound="1" upperBound="-1"
        eType="#//InterfacedComp" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instance" eSuperTypes="#//Composition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//NodeDecl"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg" upperBound="-1" eType="#//Arg"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" unique="false" upperBound="-1"
        eType="#//PortDecl"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfacedComp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composition" lowerBound="1"
        eType="#//Composition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="syncPort" upperBound="-1"
        eType="#//PortDecl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exp" abstract="true" interface="true"
      eSuperTypes="#//Arg"/>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="#//Statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NullStmt" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment" abstract="true" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Communication" abstract="true" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="#//PortDecl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhileStmt" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Exp" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfStmt" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Exp" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="then" lowerBound="1" eType="#//Statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" lowerBound="1" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Select" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" lowerBound="1"
        upperBound="-1" eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="To" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dest" lowerBound="1" eType="#//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wait" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mini" lowerBound="1" eType="#//MinBound"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="maxi" lowerBound="1" eType="#//MaxBound"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeterministicAssignment" eSuperTypes="#//Assignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignment" lowerBound="1"
        upperBound="-1" eType="#//SingleAssignment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NonDeterministicAssignment" eSuperTypes="#//Assignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" upperBound="-1"
        eType="#//Pattern" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Exp"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingleAssignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="#//Pattern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" eType="#//Exp"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnExp" eSuperTypes="#//Exp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" lowerBound="1" eType="#//Exp"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unop" lowerBound="1" eType="#//UnOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinExp" eSuperTypes="#//Exp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//Exp"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//Exp"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="binOp" lowerBound="1" eType="#//BinOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UnOp">
    <eLiterals name="UMINUS"/>
    <eLiterals name="UDOLLAR" value="1"/>
    <eLiterals name="UNOT" value="2"/>
    <eLiterals name="UFULL" value="3"/>
    <eLiterals name="UEMPTY" value="4"/>
    <eLiterals name="DEQUEUE" value="5"/>
    <eLiterals name="FIRST" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BinOp">
    <eLiterals name="BOR" literal="BOR"/>
    <eLiterals name="BAND" value="1" literal="BAND"/>
    <eLiterals name="BEQ" value="2" literal="BEQ"/>
    <eLiterals name="BNE" value="3" literal="BNE"/>
    <eLiterals name="BLT" value="4" literal="BLT"/>
    <eLiterals name="BGT" value="5" literal="BGT"/>
    <eLiterals name="BLE" value="6" literal="BLE"/>
    <eLiterals name="BGE" value="7" literal="BGE"/>
    <eLiterals name="BADD" value="8" literal="BADD"/>
    <eLiterals name="BMINUS" value="9" literal="BMINUS"/>
    <eLiterals name="BMUL" value="10" literal="BMUL"/>
    <eLiterals name="BDIV" value="11" literal="BDIV"/>
    <eLiterals name="BMOD" value="12" literal="BMOD"/>
    <eLiterals name="ENQUEUE" value="13" literal="ENQUEUE"/>
    <eLiterals name="APPEND" value="14"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NatLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoolLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VarRef" eSuperTypes="#//Pattern #//Exp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="decl" lowerBound="1" eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayElem" eSuperTypes="#//Exp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="array" lowerBound="1" eType="#//Exp"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" lowerBound="1" eType="#//Exp"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecordElem" eSuperTypes="#//Exp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="record" lowerBound="1"
        eType="#//Exp" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="field" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InlineQueue" eSuperTypes="#//InlineCollection"/>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BasicType" abstract="true" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="BoolType" eSuperTypes="#//BasicType"/>
  <eClassifiers xsi:type="ecore:EClass" name="NatType" eSuperTypes="#//BasicType"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntType" eSuperTypes="#//BasicType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Interval" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mini" lowerBound="1" eType="#//Exp"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="maxi" lowerBound="1" eType="#//Exp"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Record" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" lowerBound="1" upperBound="-1"
        eType="#//Field" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field" eSuperTypes="#//LabeledType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Array" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" lowerBound="1" eType="#//Exp"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Queue" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" lowerBound="1" eType="#//Exp"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeId" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="decl" lowerBound="1" eType="#//TypeDecl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Channel" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Profile" eSuperTypes="#//Channel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" upperBound="-1" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InlineArray" eSuperTypes="#//InlineCollection"/>
  <eClassifiers xsi:type="ecore:EClass" name="InlineRecord" eSuperTypes="#//Exp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" upperBound="-1"
        eType="#//ValuedField" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValuedField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="field" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//Exp"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Synchronization" eSuperTypes="#//Communication"/>
  <eClassifiers xsi:type="ecore:EClass" name="Reception" eSuperTypes="#//Communication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" lowerBound="1"
        upperBound="-1" eType="#//Pattern" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="where" eType="#//Exp" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Emission" eSuperTypes="#//Communication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg" upperBound="-1" eType="#//Exp"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Seq" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalPortDecl" eSuperTypes="#//PortDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mini" lowerBound="1" eType="#//MinBound"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="maxi" lowerBound="1" eType="#//MaxBound"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParamPortDecl" eSuperTypes="#//PortDecl"/>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Priority">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inf" lowerBound="1" upperBound="-1"
        eType="#//PortDecl"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sup" lowerBound="1" upperBound="-1"
        eType="#//PortDecl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstrExp" eSuperTypes="#//Exp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg" eType="#//Exp" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Union" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constr" lowerBound="1"
        upperBound="-1" eType="#//Constr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConstrPattern" eSuperTypes="#//Pattern">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg" eType="#//Pattern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayPattern" eSuperTypes="#//Pattern">
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" lowerBound="1" eType="#//Exp"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="array" lowerBound="1" eType="#//Pattern"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldPattern" eSuperTypes="#//Pattern">
    <eStructuralFeatures xsi:type="ecore:EReference" name="record" lowerBound="1"
        eType="#//Pattern" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="field" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnyPattern" eSuperTypes="#//Pattern"/>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" abstract="true" eSuperTypes="#//Exp #//Pattern"/>
  <eClassifiers xsi:type="ecore:EClass" name="CaseStmt" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" upperBound="-1" eType="#//Rule"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" lowerBound="1" eType="#//Exp"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="#//Pattern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Arg" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="RefArg" eSuperTypes="#//Arg">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1" eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantDecl" eSuperTypes="#//Declaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//Exp"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantRef" eSuperTypes="#//Exp #//Pattern">
    <eStructuralFeatures xsi:type="ecore:EReference" name="decl" lowerBound="1" eType="#//ConstantDecl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InlineCollection" abstract="true" eSuperTypes="#//Exp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elem" upperBound="-1" eType="#//Exp"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constr" eSuperTypes="#//LabeledType"/>
  <eClassifiers xsi:type="ecore:EClass" name="LabeledType" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FiniteBound" eSuperTypes="#//MinBound #//MaxBound">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strict" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InfiniteBound" eSuperTypes="#//MaxBound"/>
  <eClassifiers xsi:type="ecore:EClass" name="MinBound" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MaxBound" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CondExp" eSuperTypes="#//Exp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cond" lowerBound="1" eType="#//Exp"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iff" lowerBound="1" eType="#//Exp"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ift" lowerBound="1" eType="#//Exp"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Foreach" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//Statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iter" lowerBound="1" eType="#//LocalVariable"/>
  </eClassifiers>
</ecore:EPackage>
