<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="graphgenerators"
    nsURI="http:///org/eclipse/stem/graphgenerators/graphgenerators.ecore" nsPrefix="org.eclipse.stem.graphgenerators">
  <eClassifiers xsi:type="ecore:EClass" name="GraphGenerator" abstract="true" eSuperTypes="../../org.eclipse.stem.core/model/common.ecore#//Identifiable">
    <eOperations name="getGraph" eType="ecore:EClass ../../org.eclipse.stem.core/model/graph.ecore#//Graph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LatticeGraphGenerator" abstract="true"
      eSuperTypes="#//GraphGenerator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useNearestNeighbors" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useNextNearestNeighbors"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="periodicBoundaries" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SquareLatticeGraphGenerator" eSuperTypes="#//LatticeGraphGenerator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xSize" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="10"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ySize" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="10"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="area" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="2025"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MigrationEdgeGraphGenerator" eSuperTypes="#//GraphGenerator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType ../../org.eclipse.stem.core/model/graph.ecore#//URI"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="migrationRate" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="0.1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="population" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="human"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlateCarreeGlobeGraphGenerator" eSuperTypes="#//LatticeGraphGenerator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angularStep" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="10"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="radius" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="6371.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PajekNetGraphGenerator" eSuperTypes="#//GraphGenerator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataFile_net" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="area" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="100"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zoomFactor" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="1000"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="colArea" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
