<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="iotsystem" nsURI="http://www.uniandes.edu.co/iot/system" nsPrefix="iotsystem">
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" eSuperTypes="#//Device"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EnvironmentConditions">
    <eLiterals name="TEMPERATURE" literal="TEMPERATURE"/>
    <eLiterals name="SOUND" value="1" literal="SOUND"/>
    <eLiterals name="LIGHT" value="2" literal="LIGHT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Device" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="consumes" lowerBound="1"
        upperBound="-1" eType="#//Resource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigitalArtifact" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//Resource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//Rule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actuator" eSuperTypes="#//Device"/>
  <eClassifiers xsi:type="ecore:EClass" name="Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="measurement" lowerBound="1"
        eType="#//EnvironmentConditions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" lowerBound="1"
        upperBound="-1" eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Condition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="action" lowerBound="1"
        eType="#//Actions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalEntity" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="devices" upperBound="-1"
        eType="#//Device" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Actions">
    <eLiterals name="SMS" literal="SMS"/>
    <eLiterals name="EMAIL" value="1" literal="EMAIL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IotSystem" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="physicalEntities" lowerBound="1"
        upperBound="-1" eType="#//PhysicalEntity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="digitalArtifacts" lowerBound="1"
        upperBound="-1" eType="#//DigitalArtifact" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RelationalOperator">
    <eLiterals name="MINOR" literal="MINOR"/>
    <eLiterals name="MINOREQUAL" value="1" literal="MINOREQUAL"/>
    <eLiterals name="EQUAL" value="2" literal="EQUAL"/>
    <eLiterals name="DIFFERENT" value="3" literal="DIFFERENT"/>
    <eLiterals name="MAJOR" value="4" literal="MAJOR"/>
    <eLiterals name="MAJOREQUAL" value="5" literal="MAJOREQUAL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expectedValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationalOperator" lowerBound="1"
        eType="#//RelationalOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//Sensor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
