<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="junitmodel" nsURI="http://eclipse.org/testview/junitmodel" nsPrefix="junitmodel">
  <eClassifiers xsi:type="ecore:EClass" name="JUnitTestCase" eSuperTypes="../../org.eclipse.ui.testview/model/TestModel.ecore#//TestCaseElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="JUnitTestSuite" eSuperTypes="../../org.eclipse.ui.testview/model/TestModel.ecore#//TestContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="JUnitRoot" eSuperTypes="../../org.eclipse.ui.testview/model/TestModel.ecore#//TestRoot"/>
  <eClassifiers xsi:type="ecore:EClass" name="JUnitProblem" eSuperTypes="../../org.eclipse.ui.testview/model/TestModel.ecore#//TestProblem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastTraceWasFiltered" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JUnitComparisonProblem" eSuperTypes="#//JUnitProblem ../../org.eclipse.ui.testview/model/TestModel.ecore#//ComparisonProblem"/>
  <eClassifiers xsi:type="ecore:EClass" name="JUnitTraceStackframe" eSuperTypes="../../org.eclipse.ui.testview/model/TestModel.ecore#//TraceStackframe"/>
</ecore:EPackage>
