<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MARTE_Library"
    nsURI="http:///MARTE_Library.ecore" nsPrefix="MARTE_Library">
  <eSubpackages name="MeasurementUnits" nsURI="http:///MARTE_Library/MeasurementUnits.ecore"
      nsPrefix="MARTE_Library.MeasurementUnits">
    <eClassifiers xsi:type="ecore:EEnum" name="TimeUnitKind">
      <eLiterals name="s"/>
      <eLiterals name="tick" value="1"/>
      <eLiterals name="ms" value="2"/>
      <eLiterals name="us" value="3"/>
      <eLiterals name="min" value="4"/>
      <eLiterals name="hrs" value="5"/>
      <eLiterals name="day" value="6"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="PowerUnitKind">
      <eLiterals name="W"/>
      <eLiterals name="mW" value="1"/>
      <eLiterals name="KW" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="FrequencyUnitKind">
      <eLiterals name="Hz"/>
      <eLiterals name="KHz" value="1"/>
      <eLiterals name="MHz" value="2"/>
      <eLiterals name="GHz" value="3"/>
      <eLiterals name="rpm" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="DataSizeUnitKind">
      <eLiterals name="bit"/>
      <eLiterals name="Byte" value="1"/>
      <eLiterals name="KB" value="2"/>
      <eLiterals name="MB" value="3"/>
      <eLiterals name="GB" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="DataTxRateUnitKind">
      <eLiterals name="b_per_s"/>
      <eLiterals name="Kb_per_s" value="1"/>
      <eLiterals name="Mb_per_s" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="EnergyUnitKind">
      <eLiterals name="J"/>
      <eLiterals name="KJ" value="1"/>
      <eLiterals name="Wh" value="2"/>
      <eLiterals name="KWh" value="3"/>
      <eLiterals name="mWh" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="LengthUnitKind">
      <eLiterals name="m"/>
      <eLiterals name="cm" value="1"/>
      <eLiterals name="mm" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="AreaUnitKind">
      <eLiterals name="mm2"/>
      <eLiterals name="um2" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="WeightUnitKind">
      <eLiterals name="g"/>
      <eLiterals name="mg" value="1"/>
      <eLiterals name="kg" value="2"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="GRM_BasicTypes" nsURI="http:///MARTE_Library/GRM_BasicTypes.ecore"
      nsPrefix="MARTE_Library.GRM_BasicTypes">
    <eClassifiers xsi:type="ecore:EClass" name="EDF_Parameters">
      <eStructuralFeatures xsi:type="ecore:EReference" name="deadline" ordered="false"
          unique="false" eType="#//BasicNFP_Types/NFP_Duration" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SchedPolicyKind">
      <eLiterals name="EarliestDeadlineFirst"/>
      <eLiterals name="FIFO" value="1"/>
      <eLiterals name="FixedPriority" value="2"/>
      <eLiterals name="LeastLaxityFirst" value="3"/>
      <eLiterals name="RoundRobin" value="4"/>
      <eLiterals name="TimeTableDriven" value="5"/>
      <eLiterals name="Undef" value="6"/>
      <eLiterals name="Other" value="7"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ProtectProtocolKind">
      <eLiterals name="FIFO"/>
      <eLiterals name="NoPreemption" value="1"/>
      <eLiterals name="PriorityCeiling" value="2"/>
      <eLiterals name="PriorityInheritance" value="3"/>
      <eLiterals name="StackBased" value="4"/>
      <eLiterals name="Undef" value="5"/>
      <eLiterals name="Other" value="6"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="PeriodicServerKind">
      <eLiterals name="Sporadic"/>
      <eLiterals name="Deferrable" value="1"/>
      <eLiterals name="Undef" value="2"/>
      <eLiterals name="Other" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SchedParameters">
      <eStructuralFeatures xsi:type="ecore:EReference" name="edf" ordered="false"
          unique="false" eType="#//GRM_BasicTypes/EDF_Parameters" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fp" ordered="false" unique="false"
          eType="#//GRM_BasicTypes/FixedPriorityParameters" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pooling" ordered="false"
          unique="false" eType="#//GRM_BasicTypes/PoolingParameters" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="server" ordered="false"
          unique="false" eType="#//GRM_BasicTypes/PeriodicServerParameters" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableEntry" ordered="false"
          unique="false" upperBound="-1" eType="#//MARTE_PrimitivesTypes/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FixedPriorityParameters">
      <eStructuralFeatures xsi:type="ecore:EReference" name="priority" ordered="false"
          unique="false" eType="#//BasicNFP_Types/NFP_Integer" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PoolingParameters" eSuperTypes="#//GRM_BasicTypes/FixedPriorityParameters">
      <eStructuralFeatures xsi:type="ecore:EReference" name="period" ordered="false"
          unique="false" eType="#//BasicNFP_Types/NFP_Duration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="overhead" ordered="false"
          upperBound="-1" eType="#//BasicNFP_Types/NFP_Duration" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PeriodicServerParameters" eSuperTypes="#//GRM_BasicTypes/FixedPriorityParameters">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" ordered="false"
          unique="false" eType="#//GRM_BasicTypes/PeriodicServerKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="backgroundPriority" ordered="false"
          unique="false" eType="#//MARTE_PrimitivesTypes/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initialBudget" ordered="false"
          unique="false" eType="#//BasicNFP_Types/NFP_Duration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="replenishPeriod" ordered="false"
          unique="false" eType="#//BasicNFP_Types/NFP_Duration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="maxPendingReplenish"
          ordered="false" unique="false" eType="#//BasicNFP_Types/NFP_Integer" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="BasicNFP_Types" nsURI="http:///MARTE_Library/BasicNFP_Types.ecore"
      nsPrefix="MARTE_Library.BasicNFP_Types">
    <eClassifiers xsi:type="ecore:EEnum" name="SourceKind">
      <eLiterals name="est"/>
      <eLiterals name="meas" value="1"/>
      <eLiterals name="calc" value="2"/>
      <eLiterals name="req" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="DirectionKind">
      <eLiterals name="incr"/>
      <eLiterals name="decr" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="StatisticalQualifierKind">
      <eLiterals name="max"/>
      <eLiterals name="min" value="1"/>
      <eLiterals name="mean" value="2"/>
      <eLiterals name="range" value="3"/>
      <eLiterals name="percent" value="4"/>
      <eLiterals name="distrib" value="5"/>
      <eLiterals name="determ" value="6"/>
      <eLiterals name="other" value="7"/>
      <eLiterals name="variance" value="8"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NFP_CommonType">
      <eOperations name="bernoulli" ordered="false" lowerBound="1">
        <eParameters name="prob" ordered="false" lowerBound="1" eType="#//MARTE_PrimitivesTypes/Real"/>
      </eOperations>
      <eOperations name="binomial" ordered="false" lowerBound="1">
        <eParameters name="prob" ordered="false" lowerBound="1" eType="#//MARTE_PrimitivesTypes/Real"/>
        <eParameters name="trials" ordered="false" lowerBound="1" eType="#//MARTE_PrimitivesTypes/Integer"/>
      </eOperations>
      <eOperations name="exp" ordered="false" lowerBound="1">
        <eParameters name="mean" ordered="false" lowerBound="1" eType="#//MARTE_PrimitivesTypes/Real"/>
      </eOperations>
      <eOperations name="gamma" ordered="false" lowerBound="1">
        <eParameters name="k" ordered="false" lowerBound="1" eType="#//MARTE_PrimitivesTypes/Integer"/>
        <eParameters name="mean" ordered="false" lowerBound="1" eType="#//MARTE_PrimitivesTypes/Real"/>
      </eOperations>
      <eOperations name="normal" ordered="false" lowerBound="1">
        <eParameters name="mean" ordered="false" lowerBound="1" eType="#//MARTE_PrimitivesTypes/Real"/>
        <eParameters name="standDev" ordered="false" lowerBound="1" eType="#//MARTE_PrimitivesTypes/Real"/>
      </eOperations>
      <eOperations name="poisson" ordered="false" lowerBound="1">
        <eParameters name="mean" ordered="false" lowerBound="1" eType="#//MARTE_PrimitivesTypes/Real"/>
      </eOperations>
      <eOperations name="uniform" ordered="false" lowerBound="1">
        <eParameters name="min" ordered="false" lowerBound="1" eType="#//MARTE_PrimitivesTypes/Real"/>
        <eParameters name="max" ordered="false" lowerBound="1" eType="#//MARTE_PrimitivesTypes/Real"/>
      </eOperations>
      <eOperations name="gamma" ordered="false" lowerBound="1">
        <eParameters name="k" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="mean" ordered="false" lowerBound="1" eType="#//MARTE_PrimitivesTypes/Real"/>
      </eOperations>
      <eOperations name="geometric" ordered="false" lowerBound="1">
        <eParameters name="p" ordered="false" lowerBound="1" eType="#//MARTE_PrimitivesTypes/Real"/>
      </eOperations>
      <eOperations name="triangular" ordered="false" lowerBound="1">
        <eParameters name="min" ordered="false" lowerBound="1" eType="#//MARTE_PrimitivesTypes/Real"/>
        <eParameters name="max" ordered="false" lowerBound="1" eType="#//MARTE_PrimitivesTypes/Real"/>
        <eParameters name="mode" ordered="false" lowerBound="1" eType="#//MARTE_PrimitivesTypes/Real"/>
      </eOperations>
      <eOperations name="logarithmic" ordered="false" lowerBound="1">
        <eParameters name="theta" ordered="false" lowerBound="1" eType="#//MARTE_PrimitivesTypes/Real"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expr" ordered="false"
          unique="false" eType="#//MARTE_DataTypes/VSL_Expression"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" ordered="false"
          unique="false" eType="#//BasicNFP_Types/SourceKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="statQ" ordered="false"
          unique="false" eType="#//BasicNFP_Types/StatisticalQualifierKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dir" ordered="false"
          unique="false" eType="#//BasicNFP_Types/DirectionKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" ordered="false"
          unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NFP_Frequency" eSuperTypes="#//BasicNFP_Types/NFP_Real">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" ordered="false"
          unique="false" eType="#//MeasurementUnits/FrequencyUnitKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="precision" ordered="false"
          unique="false" eType="#//MARTE_PrimitivesTypes/Real"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NFP_Real" eSuperTypes="#//BasicNFP_Types/NFP_CommonType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
          unique="false" eType="#//MARTE_PrimitivesTypes/Real"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NFP_Natural" eSuperTypes="#//BasicNFP_Types/NFP_CommonType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
          unique="false" eType="#//MARTE_PrimitivesTypes/UnlimitedNatural"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NFP_Boolean" eSuperTypes="#//BasicNFP_Types/NFP_CommonType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
          unique="false" eType="#//MARTE_PrimitivesTypes/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NFP_String" eSuperTypes="#//BasicNFP_Types/NFP_CommonType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
          unique="false" eType="#//MARTE_PrimitivesTypes/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NFP_Integer" eSuperTypes="#//BasicNFP_Types/NFP_CommonType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
          unique="false" eType="#//MARTE_PrimitivesTypes/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NFP_DateTime" eSuperTypes="#//BasicNFP_Types/NFP_CommonType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
          unique="false" eType="#//MARTE_PrimitivesTypes/DateTime"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NFP_DataTxRate" eSuperTypes="#//BasicNFP_Types/NFP_Real">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" ordered="false"
          unique="false" eType="#//MeasurementUnits/DataTxRateUnitKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="precision" ordered="false"
          unique="false" eType="#//MARTE_PrimitivesTypes/Real"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NFP_Power" eSuperTypes="#//BasicNFP_Types/NFP_Real">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" ordered="false"
          unique="false" eType="#//MeasurementUnits/PowerUnitKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="precision" ordered="false"
          unique="false" eType="#//MARTE_PrimitivesTypes/Real"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NFP_DataSize" eSuperTypes="#//BasicNFP_Types/NFP_Real">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" ordered="false"
          unique="false" eType="#//MeasurementUnits/DataSizeUnitKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="precision" ordered="false"
          unique="false" eType="#//MARTE_PrimitivesTypes/Real"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NFP_Energy" eSuperTypes="#//BasicNFP_Types/NFP_Real">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" ordered="false"
          unique="false" eType="#//MeasurementUnits/EnergyUnitKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="precision" ordered="false"
          unique="false" eType="#//MARTE_PrimitivesTypes/Real"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NFP_Length" eSuperTypes="#//BasicNFP_Types/NFP_Real">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" ordered="false"
          unique="false" eType="#//MeasurementUnits/LengthUnitKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="precision" ordered="false"
          unique="false" eType="#//MARTE_PrimitivesTypes/Real"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NFP_Area" eSuperTypes="#//BasicNFP_Types/NFP_Real">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" ordered="false"
          unique="false" eType="#//MeasurementUnits/AreaUnitKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="precision" ordered="false"
          unique="false" eType="#//MARTE_PrimitivesTypes/Real"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArrivalPattern">
      <eStructuralFeatures xsi:type="ecore:EReference" name="periodic" ordered="false"
          unique="false" eType="#//BasicNFP_Types/PeriodicPattern" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="aperiodic" ordered="false"
          unique="false" eType="#//BasicNFP_Types/AperiodicPattern" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="burst" ordered="false"
          unique="false" eType="#//BasicNFP_Types/BurstPattern" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="irregular" ordered="false"
          unique="false" eType="#//BasicNFP_Types/IrregularPattern" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="closed" ordered="false"
          unique="false" eType="#//BasicNFP_Types/ClosedPattern" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sporadic" ordered="false"
          unique="false" eType="#//BasicNFP_Types/SporadicPattern" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="open" ordered="false"
          unique="false" eType="#//BasicNFP_Types/OpenPattern" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PeriodicPattern">
      <eStructuralFeatures xsi:type="ecore:EReference" name="period" ordered="false"
          unique="false" eType="#//BasicNFP_Types/NFP_Duration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="jitter" ordered="false"
          unique="false" eType="#//BasicNFP_Types/NFP_Duration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="phase" ordered="false"
          unique="false" eType="#//BasicNFP_Types/NFP_Duration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="occurrences" ordered="false"
          unique="false" eType="#//BasicNFP_Types/NFP_Integer" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AperiodicPattern">
      <eStructuralFeatures xsi:type="ecore:EReference" name="distribution" ordered="false"
          unique="false" eType="#//BasicNFP_Types/NFP_CommonType" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BurstPattern" eSuperTypes="#//BasicNFP_Types/AperiodicPattern">
      <eStructuralFeatures xsi:type="ecore:EReference" name="minInterarrival" ordered="false"
          unique="false" eType="#//BasicNFP_Types/NFP_Duration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="maxInterarrival" ordered="false"
          unique="false" eType="#//BasicNFP_Types/NFP_Duration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="minEventInterval" ordered="false"
          unique="false" eType="#//BasicNFP_Types/NFP_Duration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="maxEventInterval" ordered="false"
          unique="false" eType="#//BasicNFP_Types/NFP_Duration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="burstSize" ordered="false"
          unique="false" eType="#//BasicNFP_Types/NFP_Integer" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IrregularPattern" eSuperTypes="#//BasicNFP_Types/AperiodicPattern">
      <eStructuralFeatures xsi:type="ecore:EReference" name="phase" ordered="false"
          unique="false" eType="#//BasicNFP_Types/NFP_Duration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interarrivals" ordered="false"
          upperBound="-1" eType="#//BasicNFP_Types/NFP_Duration" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ClosedPattern">
      <eStructuralFeatures xsi:type="ecore:EReference" name="population" ordered="false"
          unique="false" eType="#//BasicNFP_Types/NFP_Integer" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="extDelay" ordered="false"
          unique="false" eType="#//BasicNFP_Types/NFP_Duration" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SporadicPattern" eSuperTypes="#//BasicNFP_Types/AperiodicPattern">
      <eStructuralFeatures xsi:type="ecore:EReference" name="minInterarrival" ordered="false"
          unique="false" eType="#//BasicNFP_Types/NFP_Duration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="maxInterarrival" ordered="false"
          unique="false" eType="#//BasicNFP_Types/NFP_Duration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="jitter" ordered="false"
          unique="false" eType="#//BasicNFP_Types/NFP_Duration" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OpenPattern">
      <eStructuralFeatures xsi:type="ecore:EReference" name="interArrivalTime" ordered="false"
          unique="false" eType="#//BasicNFP_Types/NFP_Duration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="arrivalRate" ordered="false"
          unique="false" eType="#//BasicNFP_Types/NFP_Frequency" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="arrivalProcess" ordered="false"
          unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NFP_Percentage" eSuperTypes="#//BasicNFP_Types/NFP_Real">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" ordered="false"
          unique="false" eType="#//MARTE_PrimitivesTypes/String" defaultValueLiteral="%"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NFP_Price" eSuperTypes="#//BasicNFP_Types/NFP_Real">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" ordered="false"
          unique="false" eType="#//MARTE_PrimitivesTypes/String" defaultValueLiteral="$US"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NFP_Weight" eSuperTypes="#//BasicNFP_Types/NFP_Real">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" ordered="false"
          unique="false" eType="#//MeasurementUnits/WeightUnitKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="precision" ordered="false"
          unique="false" eType="#//MARTE_PrimitivesTypes/Real"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NFP_Duration" eSuperTypes="#//BasicNFP_Types/NFP_Real">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" ordered="false"
          unique="false" eType="#//MeasurementUnits/TimeUnitKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="clock" ordered="false"
          unique="false" eType="#//MARTE_PrimitivesTypes/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="precision" ordered="false"
          unique="false" eType="#//MARTE_PrimitivesTypes/Real"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="worst" ordered="false"
          unique="false" eType="#//MARTE_PrimitivesTypes/Real"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="best" ordered="false"
          unique="false" eType="#//MARTE_PrimitivesTypes/Real"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="MARTE_DataTypes" nsURI="http:///MARTE_Library/MARTE_DataTypes.ecore"
      nsPrefix="MARTE_Library.MARTE_DataTypes">
    <eClassifiers xsi:type="ecore:EClass" name="IntegerVector">
      <eOperations name="at" ordered="false" lowerBound="1" eType="#//MARTE_PrimitivesTypes/Integer">
        <eParameters name="i" ordered="false" lowerBound="1" eType="#//MARTE_PrimitivesTypes/Integer"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vectorElem" ordered="false"
          unique="false" upperBound="-1" eType="#//MARTE_PrimitivesTypes/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerMatrix">
      <eOperations name="at" ordered="false" lowerBound="1" eType="#//MARTE_DataTypes/IntegerVector">
        <eParameters name="i" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="matrixElem" ordered="false"
          upperBound="-1" eType="#//MARTE_DataTypes/IntegerVector" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerInterval">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bound" ordered="false"
          unique="false" lowerBound="2" upperBound="2" eType="#//MARTE_PrimitivesTypes/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="TransmModeKind">
      <eLiterals name="simplex"/>
      <eLiterals name="halfDuplex" value="1"/>
      <eLiterals name="fullDuplex" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UtilityType">
      <eOperations name="eq" ordered="false" lowerBound="1" eType="#//MARTE_PrimitivesTypes/Boolean">
        <eParameters name="u" ordered="false" lowerBound="1" eType="#//MARTE_DataTypes/UtilityType"/>
      </eOperations>
      <eOperations name="lt" ordered="false" lowerBound="1" eType="#//MARTE_PrimitivesTypes/Boolean">
        <eParameters name="u" ordered="false" lowerBound="1" eType="#//MARTE_DataTypes/UtilityType"/>
      </eOperations>
      <eOperations name="gt" ordered="false" lowerBound="1" eType="#//MARTE_PrimitivesTypes/Boolean">
        <eParameters name="u" ordered="false" lowerBound="1" eType="#//MARTE_DataTypes/UtilityType"/>
      </eOperations>
      <eOperations name="le" ordered="false" lowerBound="1" eType="#//MARTE_PrimitivesTypes/Boolean">
        <eParameters name="u" ordered="false" lowerBound="1" eType="#//MARTE_DataTypes/UtilityType"/>
      </eOperations>
      <eOperations name="ge" ordered="false" lowerBound="1" eType="#//MARTE_PrimitivesTypes/Boolean">
        <eParameters name="u" ordered="false" lowerBound="1" eType="#//MARTE_DataTypes/UtilityType"/>
      </eOperations>
      <eOperations name="ne" ordered="false" lowerBound="1" eType="#//MARTE_PrimitivesTypes/Boolean">
        <eParameters name="u" ordered="false" lowerBound="1" eType="#//MARTE_DataTypes/UtilityType"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Array">
      <eTypeParameters name="T"/>
      <eOperations name="at" ordered="false" lowerBound="1">
        <eGenericType eTypeParameter="#//MARTE_DataTypes/Array/T"/>
        <eParameters name="i" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="vectorElement" ordered="false"
          upperBound="-1" containment="true">
        <eGenericType eTypeParameter="#//MARTE_DataTypes/Array/T"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Interval">
      <eTypeParameters name="T1"/>
      <eTypeParameters name="T2"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bound" ordered="false"
          lowerBound="2" upperBound="2" containment="true">
        <eGenericType eTypeParameter="#//MARTE_DataTypes/Interval/T2"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Realnterval">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bound" ordered="false"
          unique="false" lowerBound="2" upperBound="2" eType="#//MARTE_PrimitivesTypes/Real"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NFP_FrequencyInterval">
      <eStructuralFeatures xsi:type="ecore:EReference" name="bound" ordered="false"
          lowerBound="2" upperBound="2" eType="#//BasicNFP_Types/NFP_Frequency" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NFP_NaturalInterval">
      <eStructuralFeatures xsi:type="ecore:EReference" name="bound" ordered="false"
          lowerBound="2" upperBound="2" eType="#//BasicNFP_Types/NFP_Natural" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RealVector">
      <eOperations name="at" ordered="false" lowerBound="1" eType="#//MARTE_PrimitivesTypes/Real">
        <eParameters name="i" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vectorElem" ordered="false"
          unique="false" upperBound="-1" eType="#//MARTE_PrimitivesTypes/Real"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RealMatrix">
      <eOperations name="at" ordered="false" lowerBound="1">
        <eParameters name="i" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="p" ordered="false" lowerBound="1" eType="#//MARTE_DataTypes/RealVector"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="matrixElem" ordered="false"
          unique="false" upperBound="-1" eType="#//MARTE_PrimitivesTypes/Real"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="VSL_Expression" instanceTypeName="Object"/>
  </eSubpackages>
  <eSubpackages name="TimeTypesLibrary" nsURI="http:///MARTE_Library/TimeTypesLibrary.ecore"
      nsPrefix="MARTE_Library.TimeTypesLibrary">
    <eClassifiers xsi:type="ecore:EEnum" name="TimeNatureKind">
      <eLiterals name="discrete"/>
      <eLiterals name="dense" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="TimeInterpretationKind">
      <eLiterals name="duration"/>
      <eLiterals name="instant" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="EventKind">
      <eLiterals name="start"/>
      <eLiterals name="finish" value="1"/>
      <eLiterals name="send" value="2"/>
      <eLiterals name="receive" value="3"/>
      <eLiterals name="consume" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="TimeStandardKind">
      <eLiterals name="TAI"/>
      <eLiterals name="UT0" value="1"/>
      <eLiterals name="UT1" value="2"/>
      <eLiterals name="UTC" value="3"/>
      <eLiterals name="Local" value="4"/>
      <eLiterals name="TT" value="5"/>
      <eLiterals name="TBD" value="6"/>
      <eLiterals name="TCG" value="7"/>
      <eLiterals name="TCB" value="8"/>
      <eLiterals name="Sidereal" value="9"/>
      <eLiterals name="GPS" value="10"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="TimeLibrary" nsURI="http:///MARTE_Library/TimeLibrary.ecore"
      nsPrefix="MARTE_Library.TimeLibrary">
    <eClassifiers xsi:type="ecore:EClass" name="TimedValueType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" ordered="false"
          unique="false" eType="#//TimeLibrary/TUK"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
          unique="false" eType="#//MARTE_PrimitivesTypes/Real"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expr" ordered="false"
          unique="false" eType="#//TimeLibrary/ClockedValueSpecification"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="onClock" ordered="false"
          unique="false" eType="#//MARTE_PrimitivesTypes/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="TUK"/>
    <eClassifiers xsi:type="ecore:EDataType" name="ClockedValueSpecification" instanceTypeName="Object"/>
    <eClassifiers xsi:type="ecore:EEnum" name="TimeUnitKind">
      <eLiterals name="s"/>
      <eLiterals name="ms" value="1"/>
      <eLiterals name="us" value="2"/>
      <eLiterals name="ns" value="3"/>
      <eLiterals name="min" value="4"/>
      <eLiterals name="hrs" value="5"/>
      <eLiterals name="day" value="6"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="LogicalTimeUnit">
      <eLiterals name="tick"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IdealClock">
      <eOperations name="currentTime" ordered="false" lowerBound="1" eType="#//MARTE_PrimitivesTypes/Real"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="RS_Library" nsURI="http:///MARTE_Library/RS_Library.ecore" nsPrefix="MARTE_Library.RS_Library">
    <eClassifiers xsi:type="ecore:EClass" name="TilerSpecification">
      <eStructuralFeatures xsi:type="ecore:EReference" name="origin" ordered="false"
          unique="false" eType="#//MARTE_DataTypes/IntegerVector" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="paving" ordered="false"
          unique="false" lowerBound="1" eType="#//MARTE_DataTypes/IntegerMatrix" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fitting" ordered="false"
          unique="false" eType="#//MARTE_DataTypes/IntegerVector" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ShapeSpecification">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" ordered="false"
          unique="false" upperBound="-1" eType="#//MARTE_PrimitivesTypes/UnlimitedNatural"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="MARTE_PrimitivesTypes" nsURI="http:///MARTE_Library/MARTE_PrimitivesTypes.ecore"
      nsPrefix="MARTE_Library.MARTE_PrimitivesTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Integer" instanceClassName="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean" instanceClassName="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="UnlimitedNatural" instanceTypeName="Object"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="DateTime" instanceTypeName="Object"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Real" instanceTypeName="Object"/>
  </eSubpackages>
</ecore:EPackage>
