<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MediaLibrary" nsURI="MediaLibrary" nsPrefix="MediaLibrary">
  <eClassifiers xsi:type="ecore:EClass" name="Ecosystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="libraries" lowerBound="1"
        upperBound="-1" eType="#//Library" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="devices" lowerBound="1"
        upperBound="-1" eType="#//Device" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mediaSources" lowerBound="1"
        upperBound="-1" eType="#//MediaSource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mediaArtifacts" lowerBound="1"
        upperBound="-1" eType="#//Artifact" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Library">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collections" upperBound="-1"
        eType="#//MediaCollection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MediaCollection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" lowerBound="1"
        upperBound="-1" eType="#//Artifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="host" lowerBound="1" eType="#//Device"
        eOpposite="#//Device/hostOf"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="syncedDevices" lowerBound="1"
        upperBound="-1" eType="#//Device" eOpposite="#//Device/collections"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Device" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MACAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolutionWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolutionHeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hostOf" upperBound="-1"
        eType="#//MediaCollection" eOpposite="#//MediaCollection/host"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collections" upperBound="-1"
        eType="#//MediaCollection" eOpposite="#//MediaCollection/syncedDevices"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tablet" eSuperTypes="#//Device"/>
  <eClassifiers xsi:type="ecore:EClass" name="Computer" eSuperTypes="#//Device"/>
  <eClassifiers xsi:type="ecore:EClass" name="Smartphone" eSuperTypes="#//Device"/>
  <eClassifiers xsi:type="ecore:EClass" name="EReader" eSuperTypes="#//Device">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="videoEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Artifact" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" lowerBound="1"
        eType="#//MediaSource" eOpposite="#//MediaSource/contents"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DurationArtifact" abstract="true" eSuperTypes="#//Artifact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AudioBook" eSuperTypes="#//DurationArtifact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentPosition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MusicTrack" eSuperTypes="#//DurationArtifact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Video" eSuperTypes="#//DurationArtifact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fps" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ebook" eSuperTypes="#//Artifact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pages" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Image" eSuperTypes="#//Artifact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateTaken" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MediaSource" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//Artifact" eOpposite="#//Artifact/origin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SourceType">
    <eLiterals name="CD"/>
    <eLiterals name="CASSETTE" value="1"/>
    <eLiterals name="HDD" value="2"/>
    <eLiterals name="OTHER" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalSource" eSuperTypes="#//MediaSource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceType" eType="#//SourceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Store" eSuperTypes="#//MediaSource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
