<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="metaModelSM" nsURI="http://www.example.org/metaModelSM" nsPrefix="metaModelSM">
  <eClassifiers xsi:type="ecore:EClass" name="NewEClass1">
    <eStructuralFeatures xsi:type="ecore:EReference" name="neweclass2" upperBound="-1"
        eType="#//NewEClass2" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewEClass2"/>
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="region" upperBound="-1"
        eType="#//Region" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="NewDataType1" instanceTypeName="newDataType1"/>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Triggers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="region" upperBound="-1"
        eType="#//Region" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitialState" eSuperTypes="#//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="FinalState" eSuperTypes="#//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="Region">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
        eType="#//Transition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggered" upperBound="-1"
        eType="#//Triggers" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defines" upperBound="-1"
        eType="#//Guard" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Triggers">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" eType="#//Signal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Guard"/>
  <eClassifiers xsi:type="ecore:EClass" name="Signal"/>
</ecore:EPackage>
