<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="morel" nsURI="http://www.ustb.edu.cn/sei/mde/morel" nsPrefix="morel">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Section" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//SectionType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern" eSuperTypes="#//Section">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//ObjectVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkConstraints" upperBound="-1"
        eType="#//LinkConstraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalConstraints"
        upperBound="-1" eType="#//AdditionalConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Clause" eSuperTypes="#//Section">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" lowerBound="1"
        upperBound="-1" eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectVariable" eSuperTypes="#//Variable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//TypedModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveVariable" eSuperTypes="#//Variable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EDataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkConstraint" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//ObjectVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//ObjectVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleLinkConstraint" eSuperTypes="#//LinkConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnclosureLinkConstraint" eSuperTypes="#//LinkConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="forward" lowerBound="1"
        upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PathConstraint" eSuperTypes="#//LinkConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pathVariable" lowerBound="1"
        eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" lowerBound="1"
        upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SectionType">
    <eLiterals name="LHS"/>
    <eLiterals name="RHS" value="1"/>
    <eLiterals name="NAC" value="2"/>
    <eLiterals name="PAC" value="3"/>
    <eLiterals name="PRE" value="4"/>
    <eLiterals name="POST" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryModel" eSuperTypes="#//Unit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="queries" upperBound="-1"
        eType="#//Query" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedModel" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//TypedModelAction"
        defaultValueLiteral="normal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TypedModelAction">
    <eLiterals name="normal"/>
    <eLiterals name="readOnly" value="1"/>
    <eLiterals name="viewOnly" value="2"/>
    <eLiterals name="createOnly" value="3"/>
    <eLiterals name="transient" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Query" eSuperTypes="#//Pattern #//NamedElement #//Executable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Unit" abstract="true">
    <eOperations name="getTypedModel" eType="#//TypedModel">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="models" lowerBound="1"
        upperBound="-1" eType="#//TypedModel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataTypes" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EDataType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicExp" abstract="true" eSuperTypes="#//UnaryExpChild">
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" eType="#//CallPathExp"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralExp" abstract="true" eSuperTypes="#//AtomicExp"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringLiteralExp" eSuperTypes="#//LiteralExp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringSymbol" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerLiteralExp" eSuperTypes="#//LiteralExp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="integerSymbol" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RealLiteralExp" eSuperTypes="#//LiteralExp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="realSymbol" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanLiteralExp" eSuperTypes="#//LiteralExp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="boolSymbol" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UndefinedLiteralExp" eSuperTypes="#//LiteralExp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="#//UndefinedLiteral"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionLiteralExp" eSuperTypes="#//LiteralExp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumLiteralExp" eSuperTypes="#//LiteralExp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumType" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumSymbol" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EEnumLiteral"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UndefinedLiteral">
    <eLiterals name="NULL"/>
    <eLiterals name="INVALID" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeLiteralExp" eSuperTypes="#//LiteralExp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClassifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableExp" eSuperTypes="#//AtomicExp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredVariable" lowerBound="1"
        eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PredefinedVariableExp" eSuperTypes="#//AtomicExp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variable" lowerBound="1"
        eType="#//PredefinedVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PredefinedVariable">
    <eLiterals name="this" literal="@this"/>
    <eLiterals name="id" value="1" literal="@id"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NestedExp" eSuperTypes="#//AtomicExp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallPathExp" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//CallPathExp"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeaturePathExp" eSuperTypes="#//CallPathExp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="feature" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationPathExp" eSuperTypes="#//CallPathExp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="separator" lowerBound="1"
        eType="#//OperationSeparator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperationSeparator">
    <eLiterals name="dot"/>
    <eLiterals name="arrow" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoopPathExp" abstract="true" eSuperTypes="#//CallPathExp"/>
  <eClassifiers xsi:type="ecore:EClass" name="IteratorPathExp" eSuperTypes="#//LoopPathExp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//IteratorType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="firstVar" lowerBound="1"
        eType="#//Variable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="secondVar" eType="#//Variable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bodyExp" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IteratorType">
    <eLiterals name="forAll"/>
    <eLiterals name="exists" value="1"/>
    <eLiterals name="select" value="2"/>
    <eLiterals name="reject" value="3"/>
    <eLiterals name="collect" value="4"/>
    <eLiterals name="closure" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LetExp" eSuperTypes="#//Expression #//ImperativeExp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" lowerBound="1"
        upperBound="-1" eType="#//VariableWithInit" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inExp" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableWithInit" abstract="true" eSuperTypes="#//Variable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initExp" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectVariableWithInit" eSuperTypes="#//ObjectVariable #//VariableWithInit"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveVariableWithInit" eSuperTypes="#//PrimitiveVariable #//VariableWithInit"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionExp" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//BooleanImpliesExp" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenBranch" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseBranch" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanImpliesExp" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//BooleanImpliesExpChild"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//BooleanImpliesExpChild"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//BooleanOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanImpliesExpChild" abstract="true"
      eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanOrExp" eSuperTypes="#//BooleanImpliesExpChild">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" lowerBound="1"
        upperBound="-1" eType="#//BooleanOrExpChild" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operators" unique="false"
        upperBound="-1" eType="#//BooleanOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanOrExpChild" abstract="true" eSuperTypes="#//BooleanImpliesExpChild"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanAndExp" eSuperTypes="#//BooleanOrExpChild">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" lowerBound="1"
        upperBound="-1" eType="#//BooleanAndExpChild" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operators" unique="false"
        upperBound="-1" eType="#//BooleanOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanAndExpChild" abstract="true"
      eSuperTypes="#//BooleanOrExpChild"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BooleanOperator">
    <eLiterals name="and"/>
    <eLiterals name="or" value="1"/>
    <eLiterals name="not" value="2"/>
    <eLiterals name="implies" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationalExp" eSuperTypes="#//BooleanAndExpChild">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//RelationalExpChild"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//RelationalExpChild"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//RelationalOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationalExpChild" abstract="true"
      eSuperTypes="#//BooleanAndExpChild"/>
  <eClassifiers xsi:type="ecore:EEnum" name="RelationalOperator">
    <eLiterals name="equal"/>
    <eLiterals name="less" value="1"/>
    <eLiterals name="lessOrEq" value="2"/>
    <eLiterals name="greater" value="3"/>
    <eLiterals name="greaterOrEq" value="4"/>
    <eLiterals name="notEqual" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdditiveExp" eSuperTypes="#//RelationalExpChild">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" lowerBound="1"
        upperBound="-1" eType="#//AdditiveExpChild" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operators" unique="false"
        upperBound="-1" eType="#//AdditiveOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AdditiveOperator">
    <eLiterals name="plus"/>
    <eLiterals name="minus" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdditiveExpChild" abstract="true" eSuperTypes="#//RelationalExpChild"/>
  <eClassifiers xsi:type="ecore:EClass" name="MultiplicativeExp" eSuperTypes="#//AdditiveExpChild">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" lowerBound="1"
        upperBound="-1" eType="#//MultiplicativeExpChild" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operators" unique="false"
        upperBound="-1" eType="#//MultiplicativeOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MultiplicativeOperator">
    <eLiterals name="multi"/>
    <eLiterals name="div" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiplicativeExpChild" abstract="true"
      eSuperTypes="#//AdditiveExpChild"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryExp" eSuperTypes="#//MultiplicativeExpChild">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//UnaryOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" lowerBound="1" eType="#//UnaryExpChild"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryExpChild" abstract="true" eSuperTypes="#//MultiplicativeExpChild"/>
  <eClassifiers xsi:type="ecore:EEnum" name="UnaryOperator">
    <eLiterals name="plus"/>
    <eLiterals name="minus" value="1"/>
    <eLiterals name="not" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionType" abstract="true" eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EDataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementType" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClassifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrderedSetType" eSuperTypes="#//CollectionType"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceType" eSuperTypes="#//CollectionType"/>
  <eClassifiers xsi:type="ecore:EClass" name="SetType" eSuperTypes="#//CollectionType"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagType" eSuperTypes="#//CollectionType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ImperativeExp" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="BindExp" eSuperTypes="#//ImperativeExp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//VariableExp" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueExp" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PredefinedBindExp" eSuperTypes="#//ImperativeExp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//PredefinedVariableExp" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueExp" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfStatement" eSuperTypes="#//ImperativeStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//BooleanImpliesExp" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenStatement" lowerBound="1"
        eType="#//ImperativeStatement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseStatement" eType="#//ImperativeStatement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForStatement" eSuperTypes="#//ImperativeStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="iterator" lowerBound="1"
        eType="#//VariableWithInit" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="terminationExp" lowerBound="1"
        eType="#//BooleanImpliesExp" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stepExp" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bodyStatement" lowerBound="1"
        eType="#//ImperativeStatement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BlockStatement" eSuperTypes="#//ImperativeStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransformationModel" eSuperTypes="#//Unit #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//RuleElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuleElement" abstract="true" eSuperTypes="#//NamedElement #//Executable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Rule" eSuperTypes="#//RuleElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="patterns" upperBound="-1"
        eType="#//Pattern" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuleGroup" eSuperTypes="#//RuleElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//Rule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scope" eType="#//ScopeType"
        defaultValueLiteral="all"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scopeSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="order" eType="#//OrderType"
        defaultValueLiteral="default"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iteration" eType="#//IterationType"
        defaultValueLiteral="default"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxIteration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repetition" eType="#//RepetitionType"
        defaultValueLiteral="allMatches"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ScopeType">
    <eLiterals name="all"/>
    <eLiterals name="staticRandom" value="1"/>
    <eLiterals name="dynamicRandom" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OrderType">
    <eLiterals name="default"/>
    <eLiterals name="sequential" value="1"/>
    <eLiterals name="parallel" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IterationType">
    <eLiterals name="default"/>
    <eLiterals name="shuffle" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RepetitionType">
    <eLiterals name="allMatches"/>
    <eLiterals name="first" value="1"/>
    <eLiterals name="randomOne" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeclarativeStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImperativeStatement" abstract="true"
      eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReflectiveVariableExp" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayLiteralExp" eSuperTypes="#//LiteralExp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Executable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primitiveVariables" upperBound="-1"
        eType="#//PrimitiveVariable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdditionalConstraint" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrderConstraint" eSuperTypes="#//AdditionalConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base" lowerBound="1" eType="#//ObjectVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" lowerBound="1"
        upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" unique="false" lowerBound="1"
        upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AllDifferentConstraint" eSuperTypes="#//AdditionalConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveConstraint" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//PrimitiveVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiValueConstraint" eSuperTypes="#//PrimitiveConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" lowerBound="1"
        eType="#//ObjectVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueRangeConstraint" eSuperTypes="#//PrimitiveConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
