<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="myAtl" nsURI="http://www.xtext.org/example/mydsl/MyAtl" nsPrefix="myAtl">
  <eClassifiers xsi:type="ecore:EClass" name="Module">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outModels" upperBound="-1"
        eType="#//NameExpCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inModels" upperBound="-1"
        eType="#//NameExpCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="varName" eType="#//NameExpCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ModuleElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatchedRule" eSuperTypes="#//ModuleElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inPattern" eType="#//InPattern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//RuleVariableDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outPattern" eType="#//OutPattern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionBlock" eType="#//ActionBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CalledRule" eSuperTypes="#//ModuleElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//RuleVariableDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outPattern" eType="#//OutPattern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionBlock" eType="#//ActionBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryRule" eSuperTypes="#//ModuleElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//ATLParameterCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initExpression" eType="#//ExpCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Helper" eSuperTypes="#//ModuleElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" eType="#//ATLDefCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ATLDefCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="varName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//ATLParameterCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//ATLType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initExpression" eType="#//ExpCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ATLParameterCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="varName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//ATLType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuleVariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="varName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//ATLType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initExpression" eType="#//ExpCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InPattern">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//InPatternElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filter" eType="#//ExpCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InPatternElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="varName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//ATLType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutPattern">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//OutPatternElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutPatternElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleOutPatternElement" eSuperTypes="#//OutPatternElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="varName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//ATLType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
        eType="#//Binding" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForEachOutPatternElement" eSuperTypes="#//OutPatternElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="collection" eType="#//ExpCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Binding">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//ExpCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BindingStat" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//ExpCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//ExpCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ATLType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeExpCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionTypeCS" eSuperTypes="#//TypeLiteralCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedType" eType="#//TypeExpCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TupleTypeCS" eSuperTypes="#//TypeLiteralCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParts" upperBound="-1"
        eType="#//tuplePartCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="backtrack" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="tuplePartCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedType" eType="#//TypeExpCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveLiteralExpCS" eSuperTypes="#//PrimaryExpCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="TupleLiteralExpCS" eSuperTypes="#//PrimaryExpCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParts" upperBound="-1"
        eType="#//TupleLiteralPartCS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TupleLiteralPartCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedType" eType="#//TypeExpCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initExpression" eType="#//ExpCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberLiteralExpCS" eSuperTypes="#//PrimitiveLiteralExpCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringLiteralExpCS" eSuperTypes="#//PrimitiveLiteralExpCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanLiteralExpCS" eSuperTypes="#//PrimitiveLiteralExpCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnlimitedNaturalLiteralExpCS" eSuperTypes="#//PrimitiveLiteralExpCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="InvalidLiteralExpCS" eSuperTypes="#//PrimitiveLiteralExpCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="NullLiteralExpCS" eSuperTypes="#//PrimitiveLiteralExpCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeCS" eSuperTypes="#//TypeLiteralCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeLiteralCS" eSuperTypes="#//TypeExpCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeLiteralExpCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedType" eType="#//TypeLiteralCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeNameExpCS" eSuperTypes="#//TypeExpCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="element" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeExpCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="NavigatingArgCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//NavigatingArgExpCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedType" eType="#//TypeExpCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="init" eType="#//ExpCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigatingBarArgCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//NavigatingArgExpCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedType" eType="#//TypeExpCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="init" eType="#//ExpCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigatingCommaArgCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//NavigatingArgExpCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedType" eType="#//TypeExpCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="init" eType="#//ExpCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigatingSemiArgCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//NavigatingArgExpCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedType" eType="#//TypeExpCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="init" eType="#//ExpCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigatingArgExpCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="IfExpCS" eSuperTypes="#//PrimaryExpCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//ExpCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenExpression" eType="#//ExpCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseExpression" eType="#//ExpCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LetExpCS" eSuperTypes="#//PrimaryExpCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" upperBound="-1"
        eType="#//LetVariableCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="in" eType="#//ExpCS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LetVariableCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedType" eType="#//TypeExpCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initExpression" eType="#//ExpCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NestedExpCS" eSuperTypes="#//PrimaryExpCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//ExpCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelfExpCS" eSuperTypes="#//PrimaryExpCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrimaryExpCS" eSuperTypes="#//PrefixedExpCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringExpCs" eSuperTypes="#//PrimaryExpCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NameExpCS" eSuperTypes="#//IndexExpCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="element" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpCS" eSuperTypes="#//NavigatingArgExpCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="InfixedExpCS" eSuperTypes="#//ExpCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryOperatorCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InfixOperatorCS" eSuperTypes="#//BinaryOperatorCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationOperatorCS" eSuperTypes="#//BinaryOperatorCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrefixedExpCS" eSuperTypes="#//InfixedExpCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryOperatorCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexExpCS" eSuperTypes="#//NavigatingExpCS_Base">
    <eStructuralFeatures xsi:type="ecore:EReference" name="firstIndexes" upperBound="-1"
        eType="#//ExpCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="secondIndexes" upperBound="-1"
        eType="#//ExpCS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigatingExpCS_Base" eSuperTypes="#//NavigatingExpCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="NavigatingExpCS" eSuperTypes="#//PrimaryExpCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="namedExp" eType="#//NavigatingExpCS_Base"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="argument" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InfixExpCS" eSuperTypes="#//InfixedExpCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedExpression" upperBound="-1"
        eType="#//PrefixedExpCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedOperator" upperBound="-1"
        eType="#//BinaryOperatorCS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrefixExpCS" eSuperTypes="#//PrefixedExpCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedOperator" upperBound="-1"
        eType="#//UnaryOperatorCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedExpression" eType="#//PrimaryExpCS"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
