<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pascal" nsURI="http://www.ufcg.edu/compiladores/pascal/Pascal"
    nsPrefix="pascal">
  <eClassifiers xsi:type="ecore:EClass" name="Pascal">
    <eStructuralFeatures xsi:type="ecore:EReference" name="head" eType="#//program"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" upperBound="-1"
        eType="#//var_block" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scope" upperBound="-1"
        eType="#//block" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="program">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="var_block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="var_statements" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="var_decl">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="var_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="var_type" eType="#//type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="var_list">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="var_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="var_ids" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="var_type" eType="#//type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="type">
    <eLiterals name="BOOLEAN" literal="boolean"/>
    <eLiterals name="INTEGER" value="1" literal="integer"/>
    <eLiterals name="STRING" value="2" literal="string"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="atrib_block" upperBound="-1"
        eType="#//atrib" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="atrib">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="var_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" eType="#//expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="arit_expression" eSuperTypes="#//expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" upperBound="-1" eType="#//repetitive_arit_expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="repetitive_arit_expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" upperBound="-1" eType="#//repetitive_arit_expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="rel_expression" eSuperTypes="#//expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="open" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="first" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="second" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="close" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
