<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="py" nsURI="http://www.xtext.org/comp/Py" nsPrefix="py">
  <eClassifiers xsi:type="ecore:EClass" name="Wh">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" eType="#//Program"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Program">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functions" upperBound="-1"
        eType="#//FunctionP" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionP">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" eType="#//Definition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Definition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" eType="#//Input"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commands" eType="#//Commands"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" eType="#//Output"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Input">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vars" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Output">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vars" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Commands">
    <eStructuralFeatures xsi:type="ecore:EReference" name="commands" upperBound="-1"
        eType="#//Command" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cmd" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="If">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//Expr" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commands1" eType="#//Commands"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commands2" eType="#//Commands"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Nop">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nop" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Affect">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vars" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exprs" upperBound="-1"
        eType="#//Expr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="For">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//Expr" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cmds" eType="#//Commands"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Foreach">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="var" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr2" eType="#//Expr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cmd" eType="#//Commands"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="While">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//Expr" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cmds" eType="#//Commands"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprSimple">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="str" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="varSimple" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sym" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprAnd">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg1" eType="#//ExprSimple"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg2" eType="#//Expr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprOr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg1" eType="#//ExprSimple"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg2" eType="#//Expr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprCons">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lexpr" eType="#//LExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LExpr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lexpr" upperBound="-1"
        eType="#//Expr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg" upperBound="-1" eType="#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprHd">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg" eType="#//Expr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprTl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg" eType="#//Expr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprSym">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arg1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg2" upperBound="-1" eType="#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprNot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg1" eType="#//Expr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprEq">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg1" eType="#//ExprSimple"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg2" eType="#//Expr" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
