<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="platform:/plugin/no.hal.ra.model/model/ra.ecore"
    nsPrefix="ram">
  <eClassifiers xsi:type="ecore:EClass" name="Department">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employees" upperBound="-1"
        eType="#//Person" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//Course" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//Role" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semesters" upperBound="-1"
        eType="#//Semester" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="allocationFactor"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faceUrl" eType="#//URI"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="employmentFactor" eType="#//Factor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocations" upperBound="-1"
        eType="#//CourseAllocation" eOpposite="#//CourseAllocation/person"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="URI" instanceClassName="org.eclipse.emf.common.util.URI"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Factor" instanceClassName="double">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="minInclusive" value="0.0"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="maxInclusive" value="2.0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="pattern" value="(TDT|IT)\\d{4}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//CourseCode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredRoles" upperBound="-1"
        eType="#//Role"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="CourseCode" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EClass" name="Role">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factor" eType="#//Factor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Semester">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="#//SemesterYear"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//SemesterKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//CourseInstance" containment="true" eOpposite="#//CourseInstance/semester"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="SemesterYear" instanceClassName="int">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="minInclusive" value="1970"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="maxInclusive" value="2999"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SemesterKind">
    <eLiterals name="AUTUMN" literal="AUTUMN"/>
    <eLiterals name="SPRING" value="1" literal="SPRING"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CourseInstance">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="allocationFactor"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="course" eType="#//Course"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semester" eType="#//Semester"
        eOpposite="#//Semester/courses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocations" upperBound="-1"
        eType="#//CourseAllocation" containment="true" eOpposite="#//CourseAllocation/course"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CourseAllocation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="person" eType="#//Person"
        eOpposite="#//Person/allocations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factor" eType="#//Factor"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="explicitFactor" eType="#//Factor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="course" eType="#//CourseInstance"
        eOpposite="#//CourseInstance/allocations"/>
  </eClassifiers>
</ecore:EPackage>
