<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rcl" nsURI="http://gemoc.org/rover/rcl/" nsPrefix="rcl">
  <eClassifiers xsi:type="ecore:EClass" name="RoverProgram">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1" eType="//Param" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="//RclBlock" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Param">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosing" eType="//RclBlock" eOpposite="//RclBlock/stmts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VarAssignment" eSuperTypes="//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="//RoverValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conditional" eSuperTypes="//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="//RoverExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condTrue" eType="//RclBlock" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condFalse" eType="//RclBlock" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="//RoverExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="//RclBlock" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RclBlock" eSuperTypes="//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stmts" upperBound="-1" eType="//Statement" containment="true" eOpposite="//Statement/enclosing"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Query" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TemperatureQuery" eSuperTypes="//Query //NumberValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="HumidityQuery" eSuperTypes="//Query //NumberValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="MessageQuery" eSuperTypes="//Query //StringValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObstacleQuery" eSuperTypes="//Query //BooleanValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="front">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoverExpression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="NumericExpression" eSuperTypes="//RoverExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" eType="//NumberValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" eType="//NumberValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="//NumericOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringExpression" eSuperTypes="//RoverExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" eType="//StringValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" eType="//StringValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="//StringOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanExpression" eSuperTypes="//RoverExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" eType="//BooleanValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" eType="//BooleanValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="//BooleanOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoverValue" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="NumberValue" eSuperTypes="//RoverValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nValue">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringValue" eSuperTypes="//RoverValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sValue">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanValue" eSuperTypes="//RoverValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bValue">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NumericOperator">
    <eLiterals name="lt" literal="LT"/>
    <eLiterals name="eq" value="1" literal="EQ"/>
    <eLiterals name="neq" value="2" literal="NEQ"/>
    <eLiterals name="gt" value="3" literal="GT"/>
    <eLiterals name="leq" value="4" literal="LEQ"/>
    <eLiterals name="geq" value="5" literal="GEQ"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StringOperator">
    <eLiterals name="eq" literal="EQ"/>
    <eLiterals name="neq" value="1" literal="NEQ"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BooleanOperator">
    <eLiterals name="eq" literal="EQ"/>
    <eLiterals name="neq" value="1" literal="NEQ"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true" eSuperTypes="//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForwardAction" eSuperTypes="//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForwardMinAction" eSuperTypes="//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="distance" eType="//NumberValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BackwardAction" eSuperTypes="//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="BackwardMinAction" eSuperTypes="//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="distance" eType="//NumberValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TurnAction" eSuperTypes="//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="TurnDegAction" eSuperTypes="//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="degrees" eType="//NumberValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StopAction" eSuperTypes="//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="LogAction" eSuperTypes="//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SendAction" eSuperTypes="//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VarRef" eSuperTypes="//BooleanValue //NumberValue //StringValue //Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
