<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rpslPerceptionGraphMetaModel"
    nsURI="http://www.robotics.h-brs.de/rpsl_perception_graph" nsPrefix="RpslPerceptionGraphMetaModel">
  <eClassifiers xsi:type="ecore:EClass" name="PerceptionGraph">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uuid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
        upperBound="-1" eType="#//Element" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="perception_graph_property_prototype"
        upperBound="-1" eType="ecore:EClass rpsl_conceptual_space.ecore#//Prototype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="ecore:EClass rpsl_component.ecore#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Leaf" eSuperTypes="#//Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connection" lowerBound="1"
        upperBound="-1" eType="#//Connection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
        eType="#//Element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sink" lowerBound="1" eType="ecore:EClass rpsl_component.ecore#//InputPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="ecore:EClass rpsl_component.ecore#//OutputPort"/>
  </eClassifiers>
</ecore:EPackage>
