<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simplePDL" nsURI="http://ups/m2dl/TP4/simplePDL" nsPrefix="spdl">
  <eClassifiers xsi:type="ecore:EClass" name="Process">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" lowerBound="1"
        upperBound="-1" eType="#//WorkDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="workSequences" upperBound="-1"
        eType="#//WorkSequence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkDefinition" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predecessor" lowerBound="1"
        eType="#//WorkSequence" eOpposite="#//WorkSequence/linksToSuccessors"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="successor" lowerBound="1"
        eType="#//WorkSequence" eOpposite="#//WorkSequence/linksToPredecessors"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//WorkDefinitionParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkSequence">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="linkType" eType="#//WorkSequenceType"
        defaultValueLiteral="startToStart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linksToSuccessors" upperBound="-1"
        eType="#//WorkDefinition" eOpposite="#//WorkDefinition/predecessor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linksToPredecessors" upperBound="-1"
        eType="#//WorkDefinition" eOpposite="#//WorkDefinition/successor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WorkSequenceType">
    <eLiterals name="startToStart"/>
    <eLiterals name="finishToStart" value="1"/>
    <eLiterals name="startToFinish" value="2"/>
    <eLiterals name="finishTofinish" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkDefinitionParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterKind" eType="#//ParameterDirectionKind"
        defaultValueLiteral="in"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterType" lowerBound="1"
        eType="#//WorkProduct"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParameterDirectionKind">
    <eLiterals name="in"/>
    <eLiterals name="out" value="1"/>
    <eLiterals name="inout" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubProcess" eSuperTypes="#//WorkDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="#//WorkDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="WorkProduct">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
