<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="spem"
    nsURI="http://simplifiedspem/1.0" nsPrefix="spem">
  <eClassifiers xsi:type="ecore:EClass" name="Process">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" upperBound="-1"
        eType="#//Activity" containment="true" eOpposite="#//Activity/process"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="workSquences" upperBound="-1"
        eType="#//WorkSequence" containment="true" eOpposite="#//WorkSequence/process"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkToSuccessor" upperBound="-1"
        eType="#//WorkSequence" eOpposite="#//WorkSequence/predecessor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkToPredecessor" upperBound="-1"
        eType="#//WorkSequence" eOpposite="#//WorkSequence/successor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="durationmin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="durationmax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="process" lowerBound="1"
        eType="#//Process" eOpposite="#//Process/activities"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkSequence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="successor" lowerBound="1"
        eType="#//Activity" eOpposite="#//Activity/linkToPredecessor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predecessor" lowerBound="1"
        eType="#//Activity" eOpposite="#//Activity/linkToSuccessor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//WorkSequenceKind"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="process" lowerBound="1"
        eType="#//Process" eOpposite="#//Process/workSquences"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WorkSequenceKind">
    <eLiterals name="finishToFinish"/>
    <eLiterals name="finishToStart" value="1"/>
    <eLiterals name="startToStart" value="2"/>
    <eLiterals name="startToFinish" value="3"/>
  </eClassifiers>
</ecore:EPackage>
