<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="statemachines" nsURI="statemachinesexecutiondata" nsPrefix="statemachinesexecutiondata">
  <eClassifiers xsi:type="ecore:EClass" name="EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="../../org.tetrabox.examples.statemachines.abstractsyntax/model/statemachines.ecore#//CustomEvent"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
