<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="studyprogram" nsURI="https://org/tdt4250/project2/studyprogram"
    nsPrefix="org.tdt4250.project2.studyprogram">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Program">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseSemesters" lowerBound="1"
        upperBound="-1" eType="#//Semester" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specializations" upperBound="-1"
        eType="#//Specialization" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Specialization">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specializationSemesters"
        lowerBound="1" upperBound="-1" eType="#//Semester" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalSpecializations"
        upperBound="-1" eType="#//Specialization" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Semester">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="noDuplicateCourses"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="season" eType="#//Season"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slots" lowerBound="1" upperBound="-1"
        eType="#//Slot" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Season">
    <eLiterals name="Fall"/>
    <eLiterals name="Spring" value="1"/>
    <eLiterals name="Summer" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Slot">
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="selectedCourseInAvailableCourses" value="self.availableCourses->select(c | c = self.selectedCourse).size() > 0"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="selectedCourseInAvailableCourses"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="availableCourses" lowerBound="1"
        upperBound="-1" eType="#//Course"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectedCourse" lowerBound="1"
        eType="#//Course"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credits" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Department">
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//Course" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="programs" upperBound="-1"
        eType="#//Program" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
