<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="studyprogramme" nsURI="https://edu/runesb/tdt4250/assignment/studyprogramme"
    nsPrefix="edu.runesb.tdt4250.assignment.studyprogramme">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="validationDelegates" value="http://www.eclipse.org/acceleo/query/1.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="courseCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Programme" eSuperTypes="#//SemesterContainer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="integratedMastersMustHaveTenSemesters mastersMustHaveFourSemesters bachelorsMustHaveSixSemesters masterLevelValidCourseCombination"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="programmeCode" lowerBound="1"
        eType="#//ProgrammeCode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specializations" upperBound="-1"
        eType="#//Specialization" containment="true" eOpposite="#//Specialization/programme"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfYears" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="programmeType" lowerBound="1"
        eType="#//ProgrammeType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Specialization" eSuperTypes="#//SemesterContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="selectionSemester" upperBound="-2"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="programme" eType="#//Programme"
        eOpposite="#//Programme/specializations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subSpecialisations" upperBound="-1"
        eType="#//Specialization" containment="true" eOpposite="#//Specialization/parrentSpecialisation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parrentSpecialisation"
        eType="#//Specialization" eOpposite="#//Specialization/subSpecialisations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Semester">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="semesterMustHaveThirtyCredits"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="semesterMustHaveThirtyCredits" value="self.slots.course.credits->sum() == 30.0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semesterNumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" transient="true"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slots" upperBound="-1"
        eType="#//CourseSlot" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CourseSlot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="course" lowerBound="1"
        eType="#//Course"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SemesterContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="semesters" upperBound="-1"
        eType="#//Semester" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElectiveCourseList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="availableCourses" upperBound="-1"
        eType="#//Course"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="electiveCourseSlot" eType="#//ElectiveCourseSlot"
        eOpposite="#//ElectiveCourseSlot/electiveCourseList"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="University">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="courseCodesMustBeUnique"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="programmes" upperBound="-1"
        eType="#//Programme" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//Course" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Semesters" upperBound="-1"
        eType="#//Semester" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specialisations" upperBound="-1"
        eType="#//Specialization" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElectiveCourseSlot" eSuperTypes="#//CourseSlot">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="assignedCourseIsValid"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="electiveCourseList" eType="#//ElectiveCourseList"
        containment="true" eOpposite="#//ElectiveCourseList/electiveCourseSlot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedCourse" lowerBound="1"
        eType="#//Course"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompulsoryCourseSlot" eSuperTypes="#//CourseSlot"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ProgrammeCode">
    <eLiterals name="MTDT"/>
    <eLiterals name="MIDT" value="1"/>
    <eLiterals name="BIT" value="2"/>
    <eLiterals name="MIT" value="3"/>
    <eLiterals name="MTIOT" value="4"/>
    <eLiterals name="MTPROD" value="5" literal="MTPROD"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProgrammeType">
    <eLiterals name="Bachelors"/>
    <eLiterals name="Masters" value="1"/>
    <eLiterals name="IntegratedMaster" value="2"/>
  </eClassifiers>
</ecore:EPackage>
