<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="taskDSL" nsURI="http://www.ru.mars/des/robot/TaskDSL" nsPrefix="taskDSL">
  <eClassifiers xsi:type="ecore:EClass" name="DSL">
    <eStructuralFeatures xsi:type="ecore:EReference" name="missions" upperBound="-1"
        eType="#//Mission" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//Task" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mission">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" unique="false" upperBound="-1"
        eType="#//Task"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//Action"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="detector" eType="#//Detector"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="Detector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="avoiders" upperBound="-1"
        eType="#//Avoid" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DriveUntil" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" eType="#//Speed"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//Color"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="object" eType="#//Object"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Investigate" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" eType="#//Speed"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Speak" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FollowLine" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Avoid">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//Color"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="object" eType="#//Object"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="driveActions" upperBound="-1"
        eType="#//DriveAction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DriveAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="MoveBack" eSuperTypes="#//DriveAction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="meters" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TurnLeft" eSuperTypes="#//DriveAction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="degrees" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TurnRight" eSuperTypes="#//DriveAction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="degrees" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Object">
    <eLiterals name="ROCK" literal="ROCK"/>
    <eLiterals name="LAKE" value="1" literal="LAKE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Speed">
    <eLiterals name="FAST" literal="FAST"/>
    <eLiterals name="NORMAL" value="1" literal="NORMAL"/>
    <eLiterals name="SLOW" value="2" literal="SLOW"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Color">
    <eLiterals name="RED" literal="RED"/>
    <eLiterals name="GREEN" value="1" literal="GREEN"/>
    <eLiterals name="BLUE" value="2" literal="BLUE"/>
  </eClassifiers>
</ecore:EPackage>
