<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testFramework" nsURI="http://www.vmware.com/in/testframework/TestFramework"
    nsPrefix="testFramework">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="greetings" upperBound="-1"
        eType="#//Greeting" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Greeting">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testcaseValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="summaryDetails" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//FIRSTACTION"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FIRSTACTION">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checktableAction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextAction" eType="#//TABLEACTION"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TABLEACTION">
    <eStructuralFeatures xsi:type="ecore:EReference" name="identifierAction" eType="#//IDENTIFIER"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextAction" eType="#//LABEL"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IDENTIFIER">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifiervalue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LABEL">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelvalue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
