<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testcompat103"
    nsURI="http://testcompat103" nsPrefix="_testcompat103">
  <eAnnotations source="diagen">
    <details key="knownas=simple world"/>
    <details key="origin=http://org.isoe.fr"/>
    <details key="leftparent=nil" value=""/>
    <details key="rightparent=nil" value=""/>
    <details key="requires=nil" value=""/>
    <details key="context=startup"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="World" abstract="true" eSuperTypes="#//NamedElement">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="kref=things"/>
      <details key="kref=foos"/>
      <details key="kref=ec0s"/>
      <details key="kref=ec2s"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="things" upperBound="-1"
        eType="#//Thing" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="foos" upperBound="-1" eType="#//Foo"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ec0s" upperBound="-1" eType="#//EClass0"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ec2s" upperBound="-1" eType="#//EClass2"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Thing" eSuperTypes="#//NamedElement">
    <eAnnotations source="diagraph">
      <details key="node"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
        eType="#//RelatedTo" containment="true" eOpposite="#//RelatedTo/fromThing"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eAnnotations source="diagraph">
      <details key="label=name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelatedTo" eSuperTypes="#//NamedElement">
    <eAnnotations source="diagraph">
      <details key="link"/>
      <details key="cont=Thing.relations"/>
      <details key="lsrc=fromThing"/>
      <details key="ltrg=toThing"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromThing" eType="#//Thing"
        eOpposite="#//Thing/relations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toThing" eType="#//Thing"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="since" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Foo" eSuperTypes="#//NamedElement">
    <eAnnotations source="diagraph">
      <details key="node"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClass0" eSuperTypes="#//NamedElement">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="kref=e1s"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="e1s" upperBound="-1" eType="#//EClass1"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClass1" eSuperTypes="#//NamedElement">
    <eAnnotations source="diagraph">
      <details key="node"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClass2" eSuperTypes="#//EClass0">
    <eAnnotations source="diagraph">
      <details key="node"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClass3" eSuperTypes="#//World">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="pov"/>
      <details key="kref=subs"/>
      <details key="cont=EClass3.subs"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subs" upperBound="-1" eType="#//EClass3"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
