<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="xygraph" nsURI="http://www.eclipse.org/papyrus/xygraph/model"
    nsPrefix="xygraph">
  <eClassifiers xsi:type="ecore:EClass" name="XYGraphDescriptor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showLegend" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showTitle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="titleColor" eType="#//ColorDescriptor"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transparent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zoomType" eType="#//ZoomType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="axisDescriptors" upperBound="-1"
        eType="#//AxisDescriptor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceDescriptors" upperBound="-1"
        eType="#//TraceDescriptor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showPlotAreaBorder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="plotAreaBackgroundColor"
        eType="#//ColorDescriptor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="titleFont" eType="#//FontDescriptor"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataSource" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="visibleTraces" upperBound="-1"
        eType="#//TraceDescriptor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AxisDescriptor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orientation" eType="#//LinearScale_Orientation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autoScale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autoScaleThreshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.01"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="backgroundColor" eType="#//ColorDescriptor"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dashGridLine" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="foregroundColor" eType="#//ColorDescriptor"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logScale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="majorGridColor" eType="#//ColorDescriptor"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="minorGridColor" eType="#//ColorDescriptor"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minorTicksVisible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primarySide" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rangeLower" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rangeUpper" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showMajorGrid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showMinorGrid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zoomType" eType="#//ZoomType"
        defaultValueLiteral="NONE"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="titleFont" eType="#//FontDescriptor"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="font" eType="#//FontDescriptor"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autoFormat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formatPattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="############.##"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraceDescriptor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="antiAliasing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="areaAlpha" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="100"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseLine" eType="#//Trace_BaseLine"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="drawYErrorInArea" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="errorBarCapWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="4"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="errorBarColor" eType="#//ColorDescriptor"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="errorBarEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pointSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="4"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pointStyle" eType="#//Trace_PointStyle"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceColor" eType="#//ColorDescriptor"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="traceType" eType="#//Trace_TraceType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xAxis" eType="#//AxisDescriptor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xErrorBarType" eType="#//Trace_ErrorBarType"
        defaultValueLiteral="BOTH"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="yAxis" eType="#//AxisDescriptor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yErrorBarType" eType="#//Trace_ErrorBarType"
        defaultValueLiteral="BOTH"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataSource" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FontDescriptor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Arial"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="12"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="style" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColorDescriptor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="r" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="g" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="b" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ZoomType">
    <eLiterals name="NONE" value="11"/>
    <eLiterals name="RUBBERBAND_ZOOM"/>
    <eLiterals name="DYNAMIC_ZOOM" value="1"/>
    <eLiterals name="HORIZONTAL_ZOOM" value="2" literal="HORIZONTAL_ZOOM"/>
    <eLiterals name="VERTICAL_ZOOM" value="3"/>
    <eLiterals name="ZOOM_IN" value="4" literal="ZOOM_IN"/>
    <eLiterals name="ZOOM_OUT" value="5" literal="ZOOM_OUT"/>
    <eLiterals name="ZOOM_IN_HORIZONTALLY" value="6" literal="ZOOM_IN_HORIZONTALLY"/>
    <eLiterals name="ZOOM_OUT_HORIZONTALLY" value="7" literal="ZOOM_OUT_HORIZONTALLY"/>
    <eLiterals name="ZOOM_IN_VERTICALLY" value="8" literal="ZOOM_IN_VERTICALLY"/>
    <eLiterals name="ZOOM_OUT_VERTICALLY" value="9" literal="ZOOM_OUT_VERTICALLY"/>
    <eLiterals name="PANNING" value="10"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LinearScale_Orientation">
    <eLiterals name="HORIZONTAL"/>
    <eLiterals name="VERTICAL" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Trace_BaseLine">
    <eLiterals name="NEGATIVE_INFINITY"/>
    <eLiterals name="ZERO" value="1"/>
    <eLiterals name="POSITIVE_INFINITY" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Trace_PointStyle">
    <eLiterals name="NONE"/>
    <eLiterals name="POINT" value="1"/>
    <eLiterals name="CIRCLE" value="2"/>
    <eLiterals name="TRIANGLE" value="3"/>
    <eLiterals name="FILLED_TRIANGLE" value="4"/>
    <eLiterals name="SQUARE" value="5"/>
    <eLiterals name="FILLED_SQUARE" value="6"/>
    <eLiterals name="DIAMOND" value="7"/>
    <eLiterals name="FILLED_DIAMOND" value="8"/>
    <eLiterals name="XCROSS" value="9"/>
    <eLiterals name="CROSS" value="10"/>
    <eLiterals name="BAR" value="11"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Trace_TraceType">
    <eLiterals name="SOLID_LINE"/>
    <eLiterals name="DASH_LINE" value="1"/>
    <eLiterals name="POINT" value="2"/>
    <eLiterals name="BAR" value="3"/>
    <eLiterals name="AREA" value="4"/>
    <eLiterals name="LINE_AREA" value="5"/>
    <eLiterals name="STEP_VERTICALLY" value="6"/>
    <eLiterals name="STEP_HORIZONTALLY" value="7"/>
    <eLiterals name="DASHDOT_LINE" value="8"/>
    <eLiterals name="DASHDOTDOT_LINE" value="9"/>
    <eLiterals name="DOT_LINE" value="10"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Trace_ErrorBarType">
    <eLiterals name="NONE"/>
    <eLiterals name="PLUS" value="1"/>
    <eLiterals name="MINUS" value="2"/>
    <eLiterals name="BOTH" value="3"/>
  </eClassifiers>
</ecore:EPackage>
