office	Page (ViewCenterY,Double,attribute) (reviewerID,Integer,attribute) (background,Boolean,attribute) (viewScale,Double,attribute) (viewCenterX,Double,attribute) (associatedPage,Integer,attribute) (backPage,Integer,attribute) (pageElts,PageElt,ref) (p_pages,PagesCollection,ref) 
office	DocumentPropertiesCollection (template,String,attribute) (creator,String,attribute) (manager,String,attribute) (keywords,String,attribute) (hyperlinkBase_href,String,attribute) (subject,String,attribute) (description,String,attribute) (title,String,attribute) (alternateNames,String,attribute) (buildNumberCreated,String,attribute) (company,String,attribute) (buildNumberEdited,String,attribute) (category,String,attribute) (dps_visioDocument,VisioDocument,ref) (customProps,CustomPropertiesCollection,ref) (timeSaved,DateTimeType,ref) (timeEdited,DateTimeType,ref) (timeCreated,DateTimeType,ref) (timePrinted,DateTimeType,ref) 
office	Connect (toCell,String,attribute) (fromPart,Integer,attribute) (fromCell,String,attribute) (fromSheet,Integer,attribute) (toPart,Integer,attribute) (toSheet,Integer,attribute) (c_connects,ConnectsCollection,ref) 
office	DateTimeType (month,Integer,attribute) (hour,Integer,attribute) (year,Integer,attribute) (day,Integer,attribute) (minute,Integer,attribute) (second,Integer,attribute) 
office	VisioDocument (docLangId,Integer,attribute) (buildnum,Integer,attribute) (metric,Boolean,attribute) (start,Integer,attribute) (version,String,attribute) (key,String,attribute) (docPages,PagesCollection,ref) (docEmailRoutingData,EmailRoutingData,ref) (docColors,ColorsTable,ref) (docEventList,EventList,ref) (docPrintSetup,PrintSetup,ref) (docStyleSheets,StyleSheetsCollection,ref) (docFonts,FontsTable,ref) (docFaceNames,FaceNamesTable,ref) (docHeaderFooter,HeaderFooter,ref) (docProps,DocumentPropertiesCollection,ref) (docVBProjectData,VBProjectData,ref) (docWindows,WindowsInfo,ref) (docDocumentSheet,DocumentSheet,ref) (docMasters,MastersCollection,ref) (docSettings,DocumentSettingsElt,ref) (docSolutionXML,SolutionXML,ref) 
office	MasterShortCut (alignName,Integer,attribute) (shortcutHelp,String,attribute) (shortcutURL,String,attribute) (iconSize,Integer,attribute) (prompt,String,attribute) (patternFlags,Integer,attribute) (m_masterShortCuts,MastersCollection,ref) (icons,Icon,ref) 
office	Master (alignName,Integer,attribute) (hidden,Boolean,attribute) (matchByName,Boolean,attribute) (iconSize,Integer,attribute) (iconUpdate,Boolean,attribute) (baseID,String,attribute) (prompt,String,attribute) (patternFlags,Integer,attribute) (m_masters,MastersCollection,ref) (masterElts,MasterElt,ref) 
office	Geom (noLine,CellType,ref) (movesTo,MoveTo,ref) (noShow,CellType,ref) (arcsTo,ArcTo,ref) (ellipticalArcsTo,EllipticalArcTo,ref) (splineKnots,SplineKnot,ref) (infiniteLines,InfiniteLine,ref) (ellipses,Ellipse,ref) (polylinesTo,PolylineTo,ref) (splineStarts,SplineStart,ref) (linesTo,LineTo,ref) (noSnap,CellType,ref) (noFill,CellType,ref) (nurbsTo,NURBSTo,ref) 
