office	ImageRef (path,EString,attribute) (name,EString,attribute) (caption,EString,attribute) (style,EString,attribute) (clazz,EString,attribute) (image,null,ref) 
office	Document (langDefs,LangDef,ref) (glossary,Glossary,ref) (chapters,Chapter,ref) (subtitle,TextOrMarkup,ref) (parts,Part,ref) (authors,TextOrMarkup,ref) 
