tex	Item (file,EEString,attribute) (media_type,EEString,attribute) (generated,EBoolean,attribute) (fallback_style,EEString,attribute) (noToc,EBoolean,attribute) (required_modules,EEString,attribute) (id,EEString,attribute) (href,EEString,attribute) (title,EEString,attribute) (fallback,EEString,attribute) (required_namespace,EEString,attribute) (sourcePath,EEString,attribute)
