uml	Action (isAsynchronous,Boolean,attribute) (recurrence,IterationExpression,ref) (actionSequence,ActionSequence,ref) (actualArgument,Argument,ref) (script,ActionExpression,ref) (target,ObjectSetExpression,ref) 
uml	State (exit,Action,ref) (entry,Action,ref) (stateMachine,StateMachine,ref) (internalTransition,Transition,ref) (doActivity,Action,ref) (deferrableEvent,Event,ref) 
uml	Transition (stateMachine,StateMachine,ref) (effect,Action,ref) (guard,Guard,ref) (trigger,Event,ref) (source,StateVertex,ref) (target,StateVertex,ref) 
