uml	Requirement (identifier,EString,attribute) (name,EString,attribute) (priority,EInt,attribute) (isMandatory,EBoolean,attribute) (description,Description,ref) (requirementOwnedBy,Person,ref) (dependencySource,Dependency,ref) 
