office	Document (papertype,EString,attribute) (prefix,EString,attribute) (fontsize,EString,attribute) (documenttype,EString,attribute) (containscommands,Commands,ref) (containsbody,Body,ref) (containsstyles,Styles,ref) (begindoc,Begin,ref) (containsbib,Bibliography,ref) (containsabstract,Abstracte,ref) (enddoc,End,ref) (containspackages,Packages,ref) (containstitle,Title,ref) 
