office	Page (ViewCenterY,Double,attribute) (reviewerID,Integer,attribute) (background,Boolean,attribute) (viewScale,Double,attribute) (viewCenterX,Double,attribute) (associatedPage,Integer,attribute) (backPage,Integer,attribute) (pageElts,PageElt,ref) (p_pages,PagesCollection,ref) 
