office	Meta (scheme,CDATA,ref) (httpequiv,CDATA,ref) (name,CDATA,ref) (id,ID,ref) (i18n,I18n,ref) (content,CDATA,ref) 
office	Head (headelement,HeadElement,ref) (headmisc,HeadMisc,ref) (profile,URI,ref) (html,Html,ref) (id,ID,ref) (i18n,I18n,ref) 
office	Object (declare,Boolean,attribute) (objectelement,ObjectElement,ref) (data,URI,ref) (standby,Text,ref) (tabindex,Number,ref) (archive,UriList,ref) (type,ContentType,ref) (classid,URI,ref) (codetype,ContentType,ref) (codebase,URI,ref) (width,Length,ref) (name,NMTOKEN,ref) (usemap,URI,ref) (height,Length,ref) 
office	Map (name,NMTOKEN,ref) (mapelement,MapContent,ref) (style,StyleSheet,ref) (id,ID,ref) (title,Text,ref) (class,CDATA,ref) 
office	Link (charset,Charset,ref) (rev,LinkTypes,ref) (hreflang,LanguageCode,ref) (rel,LinkTypes,ref) (href,URI,ref) (media,MediaDesc,ref) (type,ContentType,ref) 
