uml	Scope (interfaceDeclaration,Parsable,attribute) (id,EString,attribute) (label,EString,attribute) (bodyReference,EObject,ref) (bodyContents,EObject,ref) (variables,null,ref) (signals,null,ref) (bodyText,null,ref) (exitActions,Action,ref) (suspensionTrigger,Action,ref) (innerActions,Action,ref) (entryActions,Action,ref) (renamings,Substitution,ref) 
