tex	PublicationPhase (maxTime,EInt,attribute) (minTime,EInt,attribute) (name,EString,attribute) (neededPerson,Researcher,ref) (rules,Rule,ref) (placeholder,PlaceHolderPP,ref) (linksToSuccessors,Sequence,ref) 
tex	Researcher (forName,EString,attribute) (name,EString,attribute) (position,EString,attribute) (reviews,Review,ref) (phaseParticipation,PublicationPhase,ref) (placeholder,PlaceHolderRs,ref) (writes,Write,ref) (papers,Paper,ref) 
