
build	Project (path,Path,ref) (xmlns,Xmlns,ref) (default,Goal,ref) (prePostGoals,PrePostGoal,ref) (taskdefs,AntTaskDef,ref) (properties,AntProperty,ref) (goals,Goal,ref) 

build	Copy (flatten,String,attribute) (file,String,attribute) (todir,String,attribute) (includeEmptyDirs,String,attribute) (tofile,String,attribute) (presservelastmodified,String,attribute) (overwrite,String,attribute) (filtering,String,attribute) (mapper,Mapper,ref) (fileset,FileSet,ref) (filterset,FilterSet,ref) 

