office	INPUT (size,EString,attribute) (maxlength,EString,attribute) (src,EString,attribute) (inputValue,EString,attribute) (name,EString,attribute) (checked,EString,attribute) (align,EString,attribute) (type,EString,attribute) 
office	EMBED (border,EString,attribute) (vspace,EString,attribute) (src,EString,attribute) (width,EString,attribute) (align,EString,attribute) (hspace,EString,attribute) (height,EString,attribute) 
office	FRAME (marginwidth,EString,attribute) (scrolling,EString,attribute) (src,EString,attribute) (noresize,EString,attribute) (name,EString,attribute) (marginheight,EString,attribute) 
office	IMG (border,EString,attribute) (vspace,EString,attribute) (src,EString,attribute) (width,EString,attribute) (alt,EString,attribute) (align,EString,attribute) (hspace,EString,attribute) (usemap,EString,attribute) (height,EString,attribute) (ismap,EString,attribute) 
