tex	WorkshopType (titconf,String,attribute) (ville,String,attribute) (edsci,String,attribute) (serie,String,attribute) (annee,String,attribute) (page,String,attribute) (edcom,String,attribute) (urldoi,String,attribute) (pays,String,attribute) 
tex	ArtOuvrageType (titouv,String,attribute) (edsci,String,attribute) (serie,String,attribute) (annee,String,attribute) (edcom,String,attribute) (urldoi,String,attribute) 
tex	Auteur (autrePrenom,String,attribute) (urlPerso,String,attribute) (nom,String,attribute) (prenom,String,attribute) (email,String,attribute) (lab,Laboratoire,ref) 
tex	MetaType (isEpj,Integer,attribute) (langue,String,attribute) (isEpl,String,attribute) (title,String,attribute) (classification,String,attribute) (financement,String,attribute) (idext,String,attribute) (datevisible,DateVisibleEnum,attribute) (researchteam,String,attribute) (collaboration,String,attribute) (comment,String,attribute) (refInterne,String,attribute) (keyword,String,attribute) 
