tex	BibtexEntryTypes (note,NoteField,ref) (month,MonthField,ref) (year,YearField,ref) (unknowns,UnknownField,ref) (title,TitleField,ref) (key,CiteKey,ref) 
tex	Book (address,AddressField,ref) (volume_number,EObject,ref) (series,SeriesField,ref) (isbn,IsbnField,ref) (publisher,PublisherField,ref) (edition,EditionField,ref) (author_editor,EObject,ref) 
