tex	Misc (note,String,attribute) (howpublished,String,attribute) (month,String,attribute) (year,String,attribute) (title,String,attribute) (authors,Author,ref) 
tex	Proceedings (volume,String,attribute) (editor,String,attribute) (number,String,attribute) (note,String,attribute) (address,String,attribute) (series,String,attribute) (organization,String,attribute) (publisher,String,attribute) 
tex	Book (volume,String,attribute) (number,String,attribute) (note,String,attribute) (address,String,attribute) (series,String,attribute) (edition,String,attribute) 
