tex	Article (volume,EString,attribute) (number,EInt,attribute) (month,EString,attribute) (year,EInt,attribute) (fromPage,EInt,attribute) (title,EString,attribute) (toPage,EInt,attribute) (journal,null,ref) 
tex	Proceedings (month,EString,attribute) (year,EInt,attribute) (isbn,EString,attribute) (title,EString,attribute) (sponsoredBy,null,ref) (publisher,null,ref) (editors,null,ref) 
tex	Book (volume,EInt,attribute) (month,EString,attribute) (year,EInt,attribute) (series,EString,attribute) (isbn,EString,attribute) (edition,EInt,attribute) (title,EString,attribute) (publisher,null,ref) 
tex	InCollection (month,EString,attribute) (year,EInt,attribute) (fromPage,EInt,attribute) (title,EString,attribute) (toPage,EInt,attribute) (bookTitle,EString,attribute) (sponsoredBy,null,ref) (publisher,null,ref) (editors,null,ref) 
tex	InProceedings (bootitle,EString,attribute) (month,EString,attribute) (year,EInt,attribute) (fromPage,EInt,attribute) (title,EString,attribute) (toPage,EInt,attribute) (organization,null,ref) (publisher,null,ref) (editors,null,ref) 
