uml	mFSM (name,EString,attribute) (component,mComp,ref) (fsmVar,mVariable,ref) (initialState,mState,ref) (finalState,mState,ref) (states,mState,ref) 
uml	mComp (name,EString,attribute) (type,EString,attribute) (FSMs,mFSM,ref) (subComps,mComp,ref) (ports,mPort,ref) (compVar,mVariable,ref) 
