uml	State (initialTime,EInt,attribute) (finalTime,EInt,attribute) (outgoing,Transition,ref) (incoming,Transition,ref) (stateMachine,StateMachine,ref) (parentState,CompositeState,ref) 
uml	Transition (initialTime,EInt,attribute) (finalTime,EInt,attribute) (stateMachine,StateMachine,ref) (guard,Guard,ref) (action,Action,ref) (source,State,ref) (trigger,Trigger,ref) (target,State,ref) 
