uml	State (orthogonal,EBoolean,attribute) (substatechartId,EString,attribute) (composite,EBoolean,attribute) (simple,EBoolean,attribute) (leaf,EBoolean,attribute) (submachine,EBoolean,attribute) (subRegions,Region,ref) (substatechart,Statechart,ref) 
